//! Cross-reference index builder.

use std::collections::HashMap;
use std::fs;

use crate::programs::ProgramDoc;
use crate::{WikiConfig, WikiResult};

/// A cross-reference entry linking entities.
#[derive(Debug, Clone)]
pub struct CrossRefEntry {
    pub source: String,
    pub target: String,
    pub relationship: String,
}

/// Build cross-reference entries from program docs and call edges.
pub fn build_crossrefs(
    programs: &[ProgramDoc],
    edges: &[open_mainframe_assess::CallEdge],
) -> Vec<CrossRefEntry> {
    let mut xrefs = Vec::new();

    // Call relationships from edges
    for edge in edges {
        xrefs.push(CrossRefEntry {
            source: edge.caller.clone(),
            target: edge.callee.clone(),
            relationship: format!("calls ({})", edge.call_type.label()),
        });
    }

    // Program-to-source relationships
    for prog in programs {
        xrefs.push(CrossRefEntry {
            source: prog.name.clone(),
            target: prog.source_path.display().to_string(),
            relationship: "defined in".to_string(),
        });
    }

    // Extract relationships from program features
    for prog in programs {
        for feature in &prog.features {
            let upper = feature.to_uppercase();

            // Copybooks
            if upper.contains("COPY") {
                xrefs.push(CrossRefEntry {
                    source: prog.name.clone(),
                    target: feature.clone(),
                    relationship: "uses copybook".to_string(),
                });
            }

            // BMS Maps
            if upper.contains("MAP") {
                xrefs.push(CrossRefEntry {
                    source: prog.name.clone(),
                    target: feature.clone(),
                    relationship: "uses BMS map".to_string(),
                });
            }

            // Datasets / Files
            if upper.contains("FILE") || upper.contains("DD") {
                xrefs.push(CrossRefEntry {
                    source: prog.name.clone(),
                    target: feature.clone(),
                    relationship: "accesses dataset".to_string(),
                });
            }

            // DB2 Tables
            if upper.contains("DB2") || upper.contains("SQL") {
                xrefs.push(CrossRefEntry {
                    source: prog.name.clone(),
                    target: feature.clone(),
                    relationship: "uses DB2/SQL".to_string(),
                });
            }
        }
    }

    xrefs
}

/// Generate the cross-reference index page.
pub fn generate_crossref_page(config: &WikiConfig, xrefs: &[CrossRefEntry]) -> WikiResult<()> {
    let mut md = String::from("# Cross-Reference Index\n\n");
    md.push_str("Master cross-reference of all entities in the system.\n\n");

    if xrefs.is_empty() {
        md.push_str("*No cross-references found.*\n");
    } else {
        // Summary statistics
        let mut by_rel: HashMap<&str, usize> = HashMap::new();
        for x in xrefs {
            *by_rel.entry(relationship_category(&x.relationship)).or_insert(0) += 1;
        }

        md.push_str("## Summary\n\n");
        md.push_str(&format!("**Total cross-references:** {}\n\n", xrefs.len()));
        md.push_str("| Relationship Type | Count |\n");
        md.push_str("|---|---|\n");
        let mut sorted_rels: Vec<_> = by_rel.iter().collect();
        sorted_rels.sort_by_key(|(k, _)| *k);
        for (rel, count) in &sorted_rels {
            md.push_str(&format!("| {} | {} |\n", rel, count));
        }
        md.push('\n');

        // Group by relationship type
        let groups = [
            ("Call Relationships", "calls"),
            ("Source Definitions", "defined in"),
            ("Copybook References", "copybook"),
            ("BMS Map References", "map"),
            ("Dataset/File Access", "dataset"),
            ("DB2/SQL Usage", "DB2/SQL"),
        ];

        for (heading, keyword) in &groups {
            let matching: Vec<&CrossRefEntry> = xrefs
                .iter()
                .filter(|x| x.relationship.contains(keyword))
                .collect();
            if matching.is_empty() {
                continue;
            }
            md.push_str(&format!("## {}\n\n", heading));
            md.push_str("| Source | Relationship | Target |\n");
            md.push_str("|--------|--------------|--------|\n");
            for x in &matching {
                md.push_str(&format!(
                    "| {} | {} | {} |\n",
                    x.source, x.relationship, x.target
                ));
            }
            md.push('\n');
        }
    }

    md.push_str("\n---\n*Generated by Mainframe Code Wiki*\n");
    fs::write(config.output_dir.join("crossref.md"), md)?;
    Ok(())
}

/// Map a relationship string to a display category.
fn relationship_category(rel: &str) -> &str {
    if rel.contains("calls") {
        "Call Relationships"
    } else if rel.contains("defined in") {
        "Source Definitions"
    } else if rel.contains("copybook") {
        "Copybook References"
    } else if rel.contains("map") {
        "BMS Map References"
    } else if rel.contains("dataset") {
        "Dataset/File Access"
    } else if rel.contains("DB2/SQL") {
        "DB2/SQL Usage"
    } else {
        "Other"
    }
}
