//! Data systems reference page generators.

use std::fs;

use crate::{WikiConfig, WikiResult};

/// Generate all data systems reference pages.
pub fn generate_data_pages(config: &WikiConfig) -> WikiResult<()> {
    let out = config.output_dir.join("data");
    fs::write(out.join("index.md"), data_index())?;
    fs::write(out.join("datasets.md"), datasets_reference())?;
    fs::write(out.join("db2.md"), db2_reference())?;
    fs::write(out.join("ims.md"), ims_reference())?;
    fs::write(out.join("idms.md"), idms_reference())?;
    fs::write(out.join("adabas.md"), adabas_reference())?;
    fs::write(out.join("encoding.md"), encoding_reference())?;
    Ok(())
}

fn data_index() -> String {
    r#"# Data Systems

Overview of the five major data management systems found on z/OS mainframes, plus dataset
organization types and encoding formats.

## Data Systems at a Glance

| System | Type | Data Model | Access Methods | Typical Use |
|--------|------|------------|----------------|-------------|
| [VSAM/Datasets](datasets.md) | File system | Sequential, keyed, relative | QSAM, BSAM, VSAM, PDS/PDSE | General-purpose file I/O, batch processing |
| [DB2](db2.md) | Relational DBMS | Tables, rows, columns | SQL (static & dynamic) | OLTP, reporting, ad-hoc queries |
| [IMS](ims.md) | Hierarchical DBMS | Segments in parent-child trees | DL/I calls (GU, GN, ISRT, etc.) | High-volume transaction processing |
| [IDMS](idms.md) | Network (CODASYL) DBMS | Records linked by sets | DML (FIND, GET, STORE, MODIFY) | Complex many-to-many relationships |
| [ADABAS](adabas.md) | Inverted-list DBMS | Files with field-level indexing | ACB direct commands (L1-L9, S1-S4) | High-performance flexible retrieval |

## Supporting Topics

| Topic | Description |
|-------|-------------|
| [Encoding](encoding.md) | EBCDIC code pages, packed decimal, zoned decimal, binary and floating-point formats |
| [Data Dictionary](datadict.md) | Unified field dictionary extracted from analyzed programs |

## Choosing a Data System

- **Simple sequential or keyed file access** -- use VSAM (KSDS for keyed, ESDS for sequential, RRDS for relative)
- **Relational queries with SQL** -- use DB2
- **Ultra-high-volume hierarchical transactions** -- use IMS
- **Complex network relationships (legacy)** -- use IDMS
- **Flexible retrieval with inverted-list indexing** -- use ADABAS

---
*Generated by Mainframe Code Wiki*
"#
    .to_string()
}

fn datasets_reference() -> String {
    r#"# Dataset Types Reference

z/OS organizes data into *datasets* -- named collections of records managed by the operating
system's data management services. This page covers all major dataset organizations,
access methods, and storage management facilities.

## VSAM (Virtual Storage Access Method)

VSAM is IBM's primary access method for direct and sequential processing of fixed-length
and variable-length records on DASD.

### VSAM Dataset Types

| Type | Full Name | Key | Use Case |
|------|-----------|-----|----------|
| KSDS | Key-Sequenced Data Set | Unique primary key | Random + sequential by key |
| ESDS | Entry-Sequenced Data Set | None (RBA addressing) | Append-only logs, sequential |
| RRDS | Relative Record Data Set | Relative record number | Fixed slots, direct by number |
| VRRDS | Variable-length RRDS | Relative record number | Variable-length direct access |
| LDS | Linear Data Set | None (byte-addressable) | Memory-mapped data, DB2 tablespaces |

### Control Interval / Control Area Structure

```
Control Area (CA)
+-----------------------------------------------+
| CI 0 | CI 1 | CI 2 | ... | CI n | Free CI(s) |
+-----------------------------------------------+

Control Interval (CI)
+----------------------------------------------------+
| Record 1 | Record 2 | ... | Free Space | CIDF | RDFs |
+----------------------------------------------------+

CIDF = Control Interval Definition Field (4 bytes: free space offset + length)
RDF  = Record Definition Field (3 bytes per record: length + control info)
```

- **CI size**: 512 to 32768 bytes (must be a multiple of 512 for DASD)
- **CA size**: determined by allocation (tracks or cylinders)

### DEFINE CLUSTER (IDCAMS)

```jcl
//DEFVSAM  EXEC PGM=IDCAMS
//SYSPRINT DD SYSOUT=*
//SYSIN    DD *
  DEFINE CLUSTER ( -
      NAME(MY.VSAM.KSDS) -
      INDEXED -
      KEYS(10 0) -
      RECORDSIZE(100 200) -
      SHAREOPTIONS(2 3) -
      FREESPACE(20 10) -
      SPEED -
    ) -
    DATA ( -
      NAME(MY.VSAM.KSDS.DATA) -
      CYLINDERS(10 5) -
      CISZ(4096) -
    ) -
    INDEX ( -
      NAME(MY.VSAM.KSDS.INDEX) -
      CYLINDERS(1 1) -
      CISZ(2048) -
    )
/*
```

### Key Parameters

| Parameter | Description |
|-----------|-------------|
| KEYS(length offset) | Primary key definition (KSDS only) |
| RECORDSIZE(avg max) | Average and maximum record sizes |
| SHAREOPTIONS(cross-region cross-system) | 1=exclusive, 2=read-share, 3=full-share, 4=full-share+buffers |
| FREESPACE(CI% CA%) | Percentage of free space in CIs and CAs for inserts |
| CISZ(bytes) | Control interval size |
| SPEED / RECOVERY | Load mode: SPEED skips preformat, RECOVERY preformats |
| REUSE / NOREUSE | Whether OPEN resets the dataset to empty |

### Alternate Index (AIX)

```
DEFINE AIX ( -
    NAME(MY.VSAM.AIX01) -
    RELATE(MY.VSAM.KSDS) -
    KEYS(15 20) -
    UNIQUEKEY -
  ) -
  DATA (NAME(MY.VSAM.AIX01.DATA)) -
  INDEX (NAME(MY.VSAM.AIX01.INDEX))

DEFINE PATH ( -
    NAME(MY.VSAM.PATH01) -
    PATHENTRY(MY.VSAM.AIX01) -
  )

BLDINDEX -
  INDATASET(MY.VSAM.KSDS) -
  OUTDATASET(MY.VSAM.AIX01)
```

## QSAM (Queued Sequential Access Method)

QSAM provides buffered sequential access with automatic blocking/deblocking. It is the
most commonly used access method for sequential files.

### DCB Parameters

| Parameter | Values | Description |
|-----------|--------|-------------|
| RECFM | F, FB, V, VB, U, FBA, VBA | Record format (Fixed, Variable, Undefined, with A=ASA/M=machine CC) |
| LRECL | 1-32760 | Logical record length |
| BLKSIZE | 1-32760 | Block size (0 = system-determined) |
| DSORG | PS | Physical sequential |
| MACRF | (GM) or (PM) | Get-Move or Put-Move |

### OPEN Modes

| Mode | Macro | Description |
|------|-------|-------------|
| INPUT | GET | Read records sequentially |
| OUTPUT | PUT | Write records (create new) |
| EXTEND | PUT | Append to existing dataset |
| INOUT | GET/PUT/PUTX | Update in place (same LRECL) |

### COBOL File Control

```cobol
       SELECT TRANS-FILE ASSIGN TO TRANFILE
           ORGANIZATION IS SEQUENTIAL
           ACCESS MODE IS SEQUENTIAL
           FILE STATUS IS WS-FILE-STATUS.
       ...
       FD TRANS-FILE
           RECORDING MODE IS F
           BLOCK CONTAINS 0 RECORDS
           RECORD CONTAINS 80 CHARACTERS.
       01 TRANS-RECORD    PIC X(80).
```

## BSAM (Basic Sequential Access Method)

BSAM provides block-level I/O without automatic deblocking. The program manages individual
blocks and must handle record boundaries.

| Macro | Description |
|-------|-------------|
| READ | Read a block into a buffer |
| WRITE | Write a block from a buffer |
| CHECK | Wait for I/O completion |
| NOTE | Return current block position (TTR) |
| POINT | Position to a specific block (TTR) |

BSAM is used when programs need control over physical block placement or need NOTE/POINT
for direct positioning within sequential datasets.

## PDS / PDSE (Partitioned Data Sets)

A PDS is a dataset divided into *members*, each identified by a 1-8 character name.
A directory at the beginning maps member names to TTR locations.

### PDS vs PDSE

| Feature | PDS | PDSE |
|---------|-----|------|
| Space reuse | No (deleted space not reclaimed) | Yes (automatic compaction) |
| Concurrent update | No | Yes (member-level locking) |
| Directory | Fixed-size, allocated at creation | Dynamic, grows as needed |
| ISPF statistics | Stored in directory user data | Stored in directory user data |
| Load modules | Supported | PDSE Program Library (PDSE/PL) |
| Maximum members | Limited by directory blocks | Virtually unlimited |
| Sharing | DISP=SHR for read | ENQ-based member-level |

### ISPF Member Statistics

```
Name     VV.MM  Created    Changed     Size  Init   Mod   ID
MYPROG   01.05  2024/01/15 2024/03/01  150   120    30    IBMUSER
```

- **VV.MM**: Version.modification level
- **Size**: Current number of lines
- **Init**: Initial number of lines
- **Mod**: Lines modified since last save

## GDG (Generation Data Groups)

GDGs manage multiple versions (generations) of a dataset under a single base name.
Each generation is a separate dataset with a generation number suffix `GnnnnV00`.

### Relative References

| Reference | Meaning |
|-----------|---------|
| MY.GDG(0) | Current (most recent) generation |
| MY.GDG(+1) | Next generation (to be created) |
| MY.GDG(-1) | Previous generation |
| MY.GDG(-2) | Two generations back |

### DEFINE GDG (IDCAMS)

```
DEFINE GDG ( -
    NAME(MY.GDG.BASE) -
    LIMIT(5) -
    SCRATCH -
    NOEMPTY -
  )
```

| Parameter | Description |
|-----------|-------------|
| LIMIT(n) | Maximum number of generations to retain (1-255) |
| SCRATCH / NOSCRATCH | Whether to delete uncataloged generations from disk |
| EMPTY / NOEMPTY | EMPTY uncatalogs all when limit reached; NOEMPTY rolls off oldest |

### JCL Example

```jcl
//STEP1   EXEC PGM=MYPROG
//INFILE  DD DSN=MY.GDG.BASE(0),DISP=SHR
//OUTFILE DD DSN=MY.GDG.BASE(+1),DISP=(NEW,CATLG),
//           SPACE=(CYL,(10,5)),
//           DCB=(RECFM=FB,LRECL=80,BLKSIZE=27920)
```

## ICF Catalog

The Integrated Catalog Facility (ICF) manages the mapping between dataset names and
their physical locations on DASD volumes.

### Catalog Hierarchy

```
Master Catalog (one per system)
  |
  +-- User Catalog A (alias: PROD.*)
  |     +-- PROD.PAYROLL.MASTER
  |     +-- PROD.PAYROLL.TRANS
  |
  +-- User Catalog B (alias: TEST.*)
        +-- TEST.PAYROLL.MASTER
```

### Catalog Operations (IDCAMS)

| Command | Description |
|---------|-------------|
| DEFINE USERCATALOG | Create a user catalog |
| DEFINE ALIAS | Map a high-level qualifier to a user catalog |
| LISTCAT | List catalog entries |
| DELETE | Remove a catalog entry |
| ALTER | Modify catalog attributes |
| EXPORT / IMPORT | Backup/restore catalog entries |
| REPRO | Copy dataset records |

## SMS (Storage Management Subsystem)

SMS automates storage management through policy-based classes assigned by ACS routines.

### SMS Classes

| Class | Purpose | Example Attributes |
|-------|---------|-------------------|
| STORCLAS (Storage Class) | Performance objectives | Availability, accessibility, response time |
| MGMTCLAS (Management Class) | Lifecycle management | Migration, backup frequency, retention |
| DATACLAS (Data Class) | Dataset attributes | RECFM, LRECL, SPACE, DSORG |
| SGCLAS (Storage Group Class) | Volume pool | List of eligible volumes |

### ACS Routine Flow

```
Dataset allocation request
    |
    v
DATACLAS ACS routine --> assigns DATACLAS
    |
    v
STORCLAS ACS routine --> assigns STORCLAS
    |
    v
MGMTCLAS ACS routine --> assigns MGMTCLAS
    |
    v
SGCLAS ACS routine --> assigns Storage Group
    |
    v
Volume selection within Storage Group
```

## HSM (DFSMShsm)

Hierarchical Storage Manager automates data migration between storage tiers and provides
backup/recovery.

### Storage Tiers

| Tier | Media | Description |
|------|-------|-------------|
| Level 0 (ML0) | Primary DASD | Active data |
| Level 1 (ML1) | Migration DASD | Migrated from primary |
| Level 2 (ML2) | Tape | Long-term migration |

### HSM Commands

| Command | Description |
|---------|-------------|
| HMIGRATE | Migrate a dataset to ML1 or ML2 |
| HRECALL | Recall a migrated dataset to ML0 |
| HBACKDS | Back up a dataset |
| HRECOVER | Recover a backed-up dataset |
| HDELETE | Delete a migrated/backed-up copy |
| ARCHDEL | Delete archive entries |

### Automatic Functions

- **Primary space management**: migrates datasets not accessed within threshold days
- **Interval migration**: migrates when volume usage exceeds high threshold
- **Automatic backup**: incremental daily, full periodic
- **Dump**: full-volume dump to tape for disaster recovery

## Tape Management (RMM)

DFSMSrmm (Removable Media Manager) tracks tape volumes and their contents.

### Tape Concepts

| Concept | Description |
|---------|-------------|
| VOLSER | Volume serial number (1-6 characters) |
| Standard labels (SL) | IBM-standard header/trailer labels |
| Non-label (NL) | No labels on tape |
| Multi-file tape | Multiple datasets on one volume |
| Multi-volume | One dataset spanning multiple volumes |
| Stacking | Multiple datasets in sequence on one volume |

### Tape Label Structure

```
VOL1 (Volume Header Label)
HDR1 (Dataset Header Label 1) -- dataset name, creation date, expiration
HDR2 (Dataset Header Label 2) -- RECFM, BLKSIZE, LRECL
TM   (Tape Mark)
<data blocks>
TM   (Tape Mark)
EOF1 (End-of-File Label 1)
EOF2 (End-of-File Label 2)
TM TM (Double Tape Mark = End of Volume)
```

---
*Generated by Mainframe Code Wiki*
"#
    .to_string()
}

fn db2_reference() -> String {
    r#"# DB2 Reference

IBM Db2 for z/OS is the primary relational database management system on the mainframe.
It provides SQL-based access to structured data with full ACID transaction support.

## SQL Data Types

| Type | Description | COBOL Equivalent |
|------|-------------|------------------|
| CHAR(n) | Fixed-length character (1-255) | PIC X(n) |
| VARCHAR(n) | Variable-length character (1-32704) | 49-level with length + data |
| INTEGER | 4-byte signed integer | PIC S9(9) COMP |
| SMALLINT | 2-byte signed integer | PIC S9(4) COMP |
| BIGINT | 8-byte signed integer | PIC S9(18) COMP |
| DECIMAL(p,s) | Packed decimal (1-31 digits) | PIC S9(p-s)V9(s) COMP-3 |
| FLOAT / DOUBLE | 8-byte floating point | COMP-2 |
| REAL | 4-byte floating point | COMP-1 |
| DATE | Calendar date (YYYY-MM-DD) | PIC X(10) |
| TIME | Time of day (HH.MM.SS) | PIC X(8) |
| TIMESTAMP | Date + time + microseconds | PIC X(26) |
| BLOB(n) | Binary large object (up to 2GB) | N/A (LOB locator) |
| CLOB(n) | Character large object (up to 2GB) | N/A (LOB locator) |
| GRAPHIC(n) | Fixed-length DBCS | PIC G(n) USAGE DISPLAY-1 |
| VARGRAPHIC(n) | Variable-length DBCS | 49-level with length + DBCS data |
| ROWID | Unique row identifier | PIC X(40) |
| XML | XML document | N/A (XML locator) |

## SQLCA (SQL Communication Area)

The SQLCA is automatically included in COBOL programs with `EXEC SQL INCLUDE SQLCA END-EXEC`.

### Key SQLCA Fields

| Field | Type | Description |
|-------|------|-------------|
| SQLCODE | INTEGER | Return code (0=OK, 100=not found, <0=error) |
| SQLERRM | VARCHAR(70) | Error message tokens |
| SQLERRP | CHAR(8) | Module detecting the error |
| SQLERRD(1) | INTEGER | (Internal) |
| SQLERRD(2) | INTEGER | (Internal) |
| SQLERRD(3) | INTEGER | Rows affected (INSERT/UPDATE/DELETE) |
| SQLERRD(4) | INTEGER | Estimated cost (PREPARE) |
| SQLERRD(5) | INTEGER | Position of error in SQL statement |
| SQLERRD(6) | INTEGER | (Internal) |
| SQLWARN0 | CHAR(1) | 'W' if any warning flag set |
| SQLWARN1 | CHAR(1) | 'W' if string truncated |
| SQLWARN2 | CHAR(1) | 'W' if NULL eliminated from function |
| SQLWARN3 | CHAR(1) | 'W' if columns > host variables |
| SQLWARN4 | CHAR(1) | 'W' if UPDATE/DELETE without WHERE |
| SQLWARN5 | CHAR(1) | 'W' if SQL not valid for current platform |
| SQLWARN6 | CHAR(1) | 'W' if date arithmetic adjusted |
| SQLWARN7 | CHAR(1) | 'W' if decimal truncated |

### Common SQLCODE Values

| SQLCODE | Meaning |
|---------|---------|
| 0 | Successful execution |
| +100 | Row not found / end of cursor |
| -117 | Number of host variables does not match |
| -180 | Invalid date/time/timestamp value |
| -204 | Object not found |
| -206 | Column not in table |
| -305 | Null value without indicator variable |
| -501 | Cursor not open |
| -803 | Duplicate key on unique index |
| -805 | Package not found |
| -811 | Singleton SELECT returned multiple rows |
| -818 | Timestamp mismatch (DBRM vs plan) |
| -904 | Unavailable resource |
| -911 | Deadlock or timeout rollback |
| -913 | Deadlock detected |

## Cursor Management

### Cursor Lifecycle

```
DECLARE --> OPEN --> FETCH (loop) --> CLOSE
```

### DECLARE CURSOR

```sql
EXEC SQL
  DECLARE EMP_CURSOR CURSOR FOR
    SELECT EMPNO, LASTNAME, SALARY
    FROM EMP
    WHERE DEPTNO = :WS-DEPT
    ORDER BY LASTNAME
    FOR FETCH ONLY
END-EXEC
```

### Cursor Options

| Option | Description |
|--------|-------------|
| FOR FETCH ONLY | Read-only cursor (allows better optimization) |
| FOR UPDATE OF col1, col2 | Updatable cursor (takes U-locks on rows) |
| WITH HOLD | Keep cursor open across COMMIT |
| SENSITIVE / INSENSITIVE | Whether cursor sees changes by others |
| WITH RETURN | Return result set to caller (stored procedure) |
| SCROLL | Allow FETCH FIRST, LAST, PRIOR, ABSOLUTE n, RELATIVE n |

### FETCH Patterns

```cobol
       EXEC SQL OPEN EMP_CURSOR END-EXEC.
       PERFORM UNTIL SQLCODE NOT = 0
           EXEC SQL
               FETCH EMP_CURSOR
               INTO :WS-EMPNO, :WS-LASTNAME, :WS-SALARY
           END-EXEC
           IF SQLCODE = 0
               PERFORM PROCESS-EMPLOYEE
           END-IF
       END-PERFORM.
       EXEC SQL CLOSE EMP_CURSOR END-EXEC.
```

## DCLGEN (Declaration Generator)

DCLGEN generates COBOL data structures from DB2 table definitions. Output goes into a
copybook included with `EXEC SQL INCLUDE member END-EXEC`.

### Example DCLGEN Output

```cobol
      *EXEC SQL DECLARE EMP TABLE
      * ( EMPNO       CHAR(6)      NOT NULL,
      *   FIRSTNAME   VARCHAR(12)  NOT NULL,
      *   LASTNAME    VARCHAR(15)  NOT NULL,
      *   SALARY      DECIMAL(9,2)          ) END-EXEC.

       01  DCLEMP.
           10 EMPNO           PIC X(6).
           10 FIRSTNAME.
              49 FIRSTNAME-LEN  PIC S9(4) COMP.
              49 FIRSTNAME-TEXT PIC X(12).
           10 LASTNAME.
              49 LASTNAME-LEN   PIC S9(4) COMP.
              49 LASTNAME-TEXT  PIC X(15).
           10 SALARY          PIC S9(7)V9(2) COMP-3.

       01  IND-EMP.
           10 IND-SALARY      PIC S9(4) COMP.
```

## Host Variables and Indicators

### Host Variable Declaration

```cobol
       WORKING-STORAGE SECTION.
       EXEC SQL BEGIN DECLARE SECTION END-EXEC.
       01 WS-EMPNO        PIC X(6).
       01 WS-SALARY       PIC S9(7)V9(2) COMP-3.
       01 WS-SALARY-IND   PIC S9(4) COMP.
       EXEC SQL END DECLARE SECTION END-EXEC.
```

### Indicator Variable Values

| Value | Meaning |
|-------|---------|
| 0 | Value is not NULL |
| -1 | Value is NULL |
| -2 | Value is NULL (result of conversion error) |
| > 0 | Original string length before truncation |

### Usage

```sql
EXEC SQL
  SELECT SALARY INTO :WS-SALARY :WS-SALARY-IND
  FROM EMP WHERE EMPNO = :WS-EMPNO
END-EXEC
```

## Bind Options

### BIND PLAN / BIND PACKAGE

| Option | Values | Description |
|--------|--------|-------------|
| ISOLATION | CS, RR, UR, RS | Lock isolation level |
| VALIDATE | RUN, BIND | When to validate authorization |
| CURRENTDATA | YES, NO | Whether to obtain data currency |
| RELEASE | COMMIT, DEALLOCATE | When to release locks |
| DEGREE | 1, ANY | Parallelism for queries |
| DYNAMICRULES | RUN, BIND, DEFINE, INVOKE | Dynamic SQL authorization context |
| QUALIFIER | schema | Default qualifier for unqualified names |
| SQLERROR | NOPACKAGE, CONTINUE | Action on SQL errors during bind |
| EXPLAIN | YES, NO | Populate PLAN_TABLE during bind |

### Isolation Levels

| Level | Abbreviation | Lock Behavior |
|-------|-------------|---------------|
| Uncommitted Read | UR | No locks acquired for read; may see uncommitted data |
| Cursor Stability | CS | Row lock held only while positioned on row |
| Read Stability | RS | Lock held on all accessed rows until commit |
| Repeatable Read | RR | Lock all accessed rows + phantom protection via key range locks |

## Static vs Dynamic SQL

| Aspect | Static SQL | Dynamic SQL |
|--------|-----------|-------------|
| SQL text | Fixed at precompile time | Built at runtime |
| Authorization | Checked at BIND time | Checked at execution time |
| Performance | Access path chosen at BIND | Access path chosen at runtime |
| DBRM | Contains SQL statements | Contains PREPARE/EXECUTE |
| Flexibility | Cannot change SQL structure | Full runtime flexibility |
| Bind required | Yes (produces package) | Package for PREPARE/EXECUTE shell |

### Dynamic SQL Example

```cobol
       01 WS-SQL-STMT    PIC X(500).
       ...
       MOVE "SELECT EMPNO, LASTNAME FROM EMP WHERE "
           "DEPTNO = ?" TO WS-SQL-STMT.
       EXEC SQL PREPARE STMT1 FROM :WS-SQL-STMT END-EXEC.
       EXEC SQL EXECUTE STMT1 USING :WS-DEPT END-EXEC.
```

## EXPLAIN and Access Path

DB2 stores access path information in PLAN_TABLE when EXPLAIN is active.

### Common Access Path Types

| Method | Description |
|--------|-------------|
| TABLESPACE SCAN | Full scan of all pages |
| INDEX SCAN | Matching or non-matching index access |
| INDEX ONLY | All columns available from index (no data access) |
| LIST PREFETCH | Read a list of RIDs, then fetch data pages |
| MULTI-INDEX | Combine multiple indexes with RID intersection/union |
| NESTED LOOP JOIN | For each outer row, scan inner table |
| MERGE SCAN JOIN | Sort both inputs, merge on join keys |
| HYBRID JOIN | Outer via index, inner via list prefetch |
| HASH JOIN | Build hash table on inner, probe with outer |

## DB2 System Tables

| Table | Description |
|-------|-------------|
| SYSIBM.SYSTABLES | All tables and views |
| SYSIBM.SYSCOLUMNS | All columns in all tables |
| SYSIBM.SYSINDEXES | All indexes |
| SYSIBM.SYSTABLESPACE | All tablespaces |
| SYSIBM.SYSDATABASE | All databases |
| SYSIBM.SYSPLAN | All application plans |
| SYSIBM.SYSPACKAGE | All packages |
| SYSIBM.SYSFOREIGNKEYS | Foreign key relationships |
| SYSIBM.SYSRELS | Referential constraints |
| SYSIBM.SYSROUTINES | Stored procedures and functions |

---
*Generated by Mainframe Code Wiki*
"#
    .to_string()
}

fn ims_reference() -> String {
    r#"# IMS Reference

IBM Information Management System (IMS) is a hierarchical database and transaction
manager. IMS databases organize data as segments arranged in parent-child trees, accessed
through DL/I (Data Language/Interface) calls.

## DL/I Calls

### Retrieval Calls

| Call | Full Name | Description |
|------|-----------|-------------|
| GU | Get Unique | Direct retrieval using a fully qualified SSA |
| GN | Get Next | Sequential retrieval of next segment in hierarchy |
| GNP | Get Next within Parent | Sequential retrieval under current parent |
| GHU | Get Hold Unique | GU with intent to update or delete |
| GHN | Get Hold Next | GN with intent to update or delete |
| GHNP | Get Hold Next within Parent | GNP with intent to update or delete |

### Update Calls

| Call | Full Name | Description |
|------|-----------|-------------|
| ISRT | Insert | Add a new segment occurrence |
| REPL | Replace | Update a segment retrieved with Get Hold |
| DLET | Delete | Delete a segment retrieved with Get Hold |

### Other Calls

| Call | Description |
|------|-------------|
| CHKP | Basic checkpoint |
| XRST | Extended restart |
| ROLB | Rollback to last checkpoint |
| ROLL | Rollback and abnormally terminate |
| PCB | Schedule a PSB for DL/I |
| TERM | Terminate PSB scheduling |
| DEQ | Release segment-level lock |
| LOG | Write to IMS log |
| STAT | Retrieve IMS statistics |

### COBOL DL/I Call Syntax

```cobol
       CALL 'CBLTDLI' USING DLI-GU
                             PCB-MASK
                             IO-AREA
                             SSA1
                             SSA2.
```

## Segment Search Argument (SSA)

### Unqualified SSA

```
SEGNAME_
```
(8-character segment name, padded with spaces)

### Qualified SSA

```
SEGNAME_(fieldname  =value)
```

### SSA Operators

| Operator | Meaning |
|----------|---------|
| = or EQ | Equal |
| >= or GE | Greater than or equal |
| <= or LE | Less than or equal |
| > or GT | Greater than |
| < or LT | Less than |
| != or NE | Not equal |

### Boolean Operators

```
SEGNAME_(field1 =valueA * field2 =valueB)    * = AND
SEGNAME_(field1 =valueA + field2 =valueB)    + = OR
```

### Command Codes

| Code | Meaning |
|------|---------|
| D | Path call (retrieve or insert at multiple levels) |
| F | First occurrence |
| L | Last occurrence |
| N | Path call -- do not replace this level |
| P | Set parentage at this level |
| U | Maintain position at this level |
| V | Maintain position at this and all higher levels |
| - | Null command code (placeholder) |

## PCB Status Codes

### Successful

| Code | Meaning |
|------|---------|
| (blanks) | Call completed successfully |
| GE | Segment not found |
| GB | End of database reached (GN/GNP) |
| GK | Segment type changed during GN |

### Error Codes

| Code | Meaning |
|------|---------|
| II | Insert rule violation (segment already exists with same key) |
| DJ | Condition code = D on ISRT, no path to parent |
| DA | Duplicate key on ISRT (unique key violation) |
| AI | Access intent violation (read-only PCB) |
| AM | PCB not available |
| FH | Field not found in segment |
| IX | ISRT not allowed for this segment |
| RX | REPL/DLET not preceded by Get Hold |
| GA | Different database record (GN crossed to new root) |
| QC | No more messages (DC environment) |
| QD | No more segments to process |

## PSB / DBD Definitions

### DBD (Database Description)

The DBD defines the physical structure of an IMS database.

```
        DBD   NAME=CUSTDB,ACCESS=HDAM,                         X
              RMNAME=(DFSHDC40,10,4,2048)
        SEGM  NAME=CUSTOMER,BYTES=200,PARENT=0
        FIELD NAME=(CUSTNO,SEQ),BYTES=8,START=1,TYPE=C
        FIELD NAME=CUSTNAME,BYTES=40,START=9,TYPE=C
        SEGM  NAME=ORDER,BYTES=100,PARENT=CUSTOMER
        FIELD NAME=(ORDERNO,SEQ),BYTES=10,START=1,TYPE=C
        SEGM  NAME=ORDLINE,BYTES=50,PARENT=ORDER
        FIELD NAME=(LINENO,SEQ),BYTES=4,START=1,TYPE=C
        DBDGEN
        FINISH
        END
```

### PSB (Program Specification Block)

The PSB defines which databases and segments a program can access.

```
        PCB   TYPE=DB,DBDNAME=CUSTDB,PROCOPT=A,KEYLEN=22
        SENSEG NAME=CUSTOMER,PARENT=0
        SENSEG NAME=ORDER,PARENT=CUSTOMER
        SENSEG NAME=ORDLINE,PARENT=ORDER
        PSBGEN LANG=COBOL,PSBNAME=MYPGMPSB
        END
```

### PROCOPT (Processing Options)

| Option | Meaning |
|--------|---------|
| G | Get (read) |
| I | Insert |
| R | Replace |
| D | Delete |
| A | All (GIRD) |
| K | Key sensitivity only |
| E | Read path only (no position) |
| L | Load |
| LS | Load with segment insert |
| O | GOx with command code only (for DEDB) |

## Database Types

| Type | Full Name | Description |
|------|-----------|-------------|
| HDAM | Hierarchical Direct Access Method | Direct access via randomizer; fast random access |
| HIDAM | Hierarchical Indexed Direct Access Method | Indexed access to root; random + sequential |
| HISAM | Hierarchical Indexed Sequential Access Method | ISAM-based; good for small databases |
| HSAM | Hierarchical Sequential Access Method | Sequential only; tape or sequential datasets |
| SHSAM | Simple HSAM | Single-segment HSAM |
| SHISAM | Simple HISAM | Single-segment HISAM (like VSAM KSDS) |
| DEDB | Data Entry Database | Fast Path; fixed-length segments; high volume |
| MSDB | Main Storage Database | Fast Path; resident in memory (deprecated) |

## MFS (Message Format Service)

MFS formats terminal I/O in IMS DC (Data Communications) environments.

### MFS Components

| Component | Description |
|-----------|-------------|
| MID (Message Input Descriptor) | Defines format of input messages from terminal |
| MOD (Message Output Descriptor) | Defines format of output messages to terminal |
| DIF (Device Input Format) | Maps physical terminal fields to logical fields |
| DOF (Device Output Format) | Maps logical fields to physical terminal positions |

### MFS Field Attributes

| Attribute | Description |
|-----------|-------------|
| ATTR=(PROT) | Protected field (display only) |
| ATTR=(UNPROT) | Unprotected field (input allowed) |
| ATTR=(NUM) | Numeric input only |
| ATTR=(MOD) | Modified data tag set |
| ATTR=(HI) | High intensity |
| ATTR=(DET) | Detectable (light pen) |

## Region Types

| Type | Full Name | Description |
|------|-----------|-------------|
| MPP | Message Processing Program | Online transaction processing; receives input message, processes, sends reply |
| BMP | Batch Message Processing | Batch with access to online databases; can process messages |
| IFP | IMS Fast Path | High-volume, short transactions using DEDBs/MSDBs |
| DLI | DL/I Batch | Standalone batch programs with DL/I access |

## IMS Connect and OTMA

### IMS Connect

IMS Connect is a TCP/IP gateway that allows distributed applications to access IMS
transactions and databases over TCP/IP.

| Feature | Description |
|---------|-------------|
| Port | Default 9999 |
| Protocol | IRM (IMS Request Message) header + data |
| Security | RACF authentication, SSL/TLS |
| Persistent sockets | Reusable connections for performance |
| RESUME TPIPE | Asynchronous output retrieval |

### OTMA (Open Transaction Manager Access)

OTMA provides a high-performance interface between IMS and external transaction managers
(e.g., CICS, WebSphere MQ) via z/OS cross-system coupling facility (XCF).

| Component | Description |
|-----------|-------------|
| OTMA client | External system (CICS, MQ, IMS Connect) |
| OTMA server | IMS itself |
| Tpipe | Named message queue for async output |
| XCF group | OTMA communication group |

---
*Generated by Mainframe Code Wiki*
"#
    .to_string()
}

fn idms_reference() -> String {
    r#"# IDMS Reference

CA IDMS (Integrated Database Management System) implements the CODASYL (Conference on
Data Systems Languages) network database model. In a network database, records are linked
via *sets* -- named, ordered relationships between owner and member record types.

## CODASYL Schema Concepts

### Schema Structure

```
Schema
  |
  +-- Area (physical storage region)
  |     +-- Records stored in pages within the area
  |
  +-- Record Type (like a table definition)
  |     +-- Elements (like columns)
  |
  +-- Set Type (named 1:N relationship between owner and member records)
        +-- Owner record type
        +-- Member record type(s)
```

### Areas

An area is a named subdivision of the database that maps to a physical DMCL (Device-Media
Control Language) area definition. Areas control physical placement and can be opened
in different modes:

| Mode | Description |
|------|-------------|
| READY EXCLUSIVE UPDATE | Exclusive access for updates |
| READY PROTECTED UPDATE | Shared read, exclusive update |
| READY SHARED UPDATE | Shared read and update |
| READY EXCLUSIVE RETRIEVAL | Exclusive read-only |
| READY PROTECTED RETRIEVAL | Shared read, no updates allowed |
| READY SHARED RETRIEVAL | Shared read-only |

### Records

Record types define the structure of data stored in the database.

| Property | Description |
|----------|-------------|
| Record name | 1-16 characters |
| Record ID | Numeric identifier |
| Location mode | CALC, VIA SET, DIRECT |
| Within area | Which area stores this record |

### Location Modes

| Mode | Description |
|------|-------------|
| CALC | Hashed on a CALC key; random placement, fast direct access |
| VIA SET | Stored near its owner in a set; good for cluster access |
| DIRECT | Application specifies db-key; full control over placement |

## Set Types

A set defines a one-to-many (owner-to-member) relationship. Each set occurrence consists
of one owner record and zero or more member records linked in a chain.

### Set Organization Modes

| Mode | Description |
|------|-------------|
| CHAIN | Doubly-linked list through NEXT/PRIOR pointers |
| INDEX | B-tree index on sort key |

### Set Order

| Order | Description |
|-------|-------------|
| FIRST | New members added at beginning (after owner) |
| LAST | New members added at end (before owner in chain) |
| NEXT | New members added after current of set |
| PRIOR | New members added before current of set |
| SORTED | Members maintained in sort key order |

### Set Membership Options

| Aspect | Options | Description |
|--------|---------|-------------|
| Mandatory / Optional | MANDATORY, OPTIONAL | Must the member always belong to a set occurrence? |
| Automatic / Manual | AUTOMATIC, MANUAL | Is the member automatically connected on STORE? |

Combinations:
- **MANDATORY AUTOMATIC**: Member always in set; connected on STORE, cannot DISCONNECT
- **MANDATORY MANUAL**: Must be CONNECTed explicitly; cannot be DISCONNECTed once connected
- **OPTIONAL AUTOMATIC**: Connected on STORE; can be DISCONNECTed
- **OPTIONAL MANUAL**: Must CONNECT/DISCONNECT explicitly

## Currency Indicators

IDMS maintains a set of *currency indicators* that track the current position in the
database. These are critical for navigation.

| Currency | Description |
|----------|-------------|
| CURRENT OF RUN-UNIT | Last record accessed by any DML statement |
| CURRENT OF AREA | Last record accessed in each area |
| CURRENT OF RECORD TYPE | Last record accessed of each record type |
| CURRENT OF SET TYPE | Last record accessed in each set type |

Currency is updated by FIND, GET, STORE, MODIFY, ERASE, CONNECT, and DISCONNECT.

### ACCEPT and Currency

```cobol
       ACCEPT DB-KEY FROM CURRENCY.
       ACCEPT DB-KEY FROM CUSTOMER CURRENCY.
       ACCEPT DB-KEY FROM ORDER-SET CURRENCY.
```

## DML Commands

### Navigation

| Command | Description |
|---------|-------------|
| FIND CALC | Find record by CALC key (hash lookup) |
| FIND DBKEY | Find record by database key |
| FIND CURRENT | Re-establish position on current record |
| FIND FIRST/LAST/NEXT/PRIOR WITHIN SET | Navigate within a set |
| FIND FIRST/LAST/NEXT/PRIOR WITHIN AREA | Navigate within an area |
| FIND OWNER WITHIN SET | Find the owner of the current member |
| FIND n WITHIN SET | Find member by sort key in indexed set |
| GET | Move current record's data to program variable |
| OBTAIN | Combined FIND + GET |

### Update

| Command | Description |
|---------|-------------|
| STORE | Insert a new record (location mode determines placement) |
| MODIFY | Update the current record |
| ERASE | Delete the current record |
| ERASE ALL | Delete the current record and all mandatory members |

### Set Operations

| Command | Description |
|---------|-------------|
| CONNECT | Add the current record as a member of a set occurrence |
| DISCONNECT | Remove the current record from a set occurrence |

### Transaction Control

| Command | Description |
|---------|-------------|
| BIND RUN-UNIT | Begin a database session |
| READY area | Open an area in a specified mode |
| COMMIT | Commit changes and release locks |
| ROLLBACK | Undo changes since last commit |
| FINISH | End the run-unit (implicit commit) |

### Error Handling

```cobol
       FIND CALC CUSTOMER.
       IF DB-STATUS-OK
           GET CUSTOMER
       ELSE
           IF DB-REC-NOT-FOUND
               DISPLAY 'Customer not found'
           ELSE
               PERFORM IDMS-ABORT
           END-IF
       END-IF.
```

### Common Status Codes

| Code | Meaning |
|------|---------|
| 0000 | Successful |
| 0307 | Record not found (FIND CALC) |
| 0326 | End of set |
| 0306 | Currency not valid |
| 1205 | Duplicate CALC key (if DUPLICATES NOT ALLOWED) |
| 0310 | End of area (area sweep) |

## Subschema

A subschema is an application's view of the schema, defining which record types, elements,
and set types the program can access. It acts as a security and simplification layer.

```cobol
       IDENTIFICATION DIVISION.
       ...
       ENVIRONMENT DIVISION.
       IDMS-CONTROL SECTION.
           PROTOCOL. MODE IS BATCH   IDMS-RECORDS MANUAL.
       ...
       DATA DIVISION.
       SCHEMA SECTION.
       DB MYSUBSCHEMA WITHIN MYSCHEMA VERSION 1.
```

## Logical Record Facility (LRF)

LRF allows definition of logical records that span multiple physical record types,
joined through set relationships. Applications issue simple GET/MODIFY/STORE/ERASE
against the logical record, and IDMS navigates the underlying physical records automatically.

```
LR PATH NAME IS LR-CUSTOMER-ORDER
    OBTAIN CUSTOMER
    OBTAIN EACH ORDER WITHIN CUST-ORD-SET.
```

## ADS/Online

Application Development System (ADS/Online) is IDMS's integrated 4GL for building
online applications. ADS dialogs combine:

- **Maps**: Screen definitions (similar to BMS maps)
- **Processes**: Business logic written in ADS dialog language
- **Responses**: Input/output flows between maps and processes
- **Menu system**: Navigation between dialogs

---
*Generated by Mainframe Code Wiki*
"#
    .to_string()
}

fn adabas_reference() -> String {
    r#"# ADABAS Reference

ADABAS (Adaptable Database System) by Software AG is an inverted-list database management
system. Unlike hierarchical or relational databases, ADABAS uses a unique inverted-list
architecture that provides fast multi-key retrieval without predefined access paths.

## Architecture

### File Structure

```
ADABAS Database
  |
  +-- File 1 (e.g., EMPLOYEES)
  |     +-- Data Storage (records in blocks)
  |     +-- Address Converter (ISN -> RABN mapping)
  |     +-- Normal Index (inverted lists for descriptors)
  |     +-- Upper Index (top levels of inverted-list tree)
  |
  +-- File 2 (e.g., DEPARTMENTS)
  |     +-- ...
```

### Key Concepts

| Concept | Description |
|---------|-------------|
| ISN | Internal Sequence Number -- unique record identifier within a file |
| RABN | Relative ADABAS Block Number -- physical block address |
| FDT | Field Definition Table -- describes all fields in a file |
| Descriptor | Indexed field (inverted-list key) |
| Superdescriptor | Composite index from multiple fields |

## FDT (Field Definition Table)

The FDT defines every field in an ADABAS file.

### Field Types

| Code | Type | Description |
|------|------|-------------|
| A | Alphanumeric | Character data (EBCDIC) |
| B | Binary | Raw binary data |
| F | Fixed-point | Signed integer (1, 2, 4 bytes) |
| G | Float | Floating point (4 or 8 bytes) |
| P | Packed decimal | Packed BCD (like COBOL COMP-3) |
| U | Unpacked decimal | Zoned decimal (like COBOL DISPLAY numeric) |
| W | Wide | Unicode / double-byte character data |

### Field Options

| Option | Description |
|--------|-------------|
| DE | Descriptor (indexed) |
| FI | Fixed storage (no compression) |
| MU | Multiple-value field (repeating) |
| NU | Null value suppression (compress out empty values) |
| PE | Periodic group (repeating group of fields) |
| UQ | Unique descriptor (no duplicate values) |

### FDT Example

```
File 1: EMPLOYEES
Level  Name  Length  Format  Options
  1    AA      8       A     DE        Employee ID (descriptor)
  1    AB      0       A               Name group
  2    AC     20       A               Last name
  2    AD     15       A               First name
  1    AE      4       P     DE        Department code (descriptor)
  1    AF      0                       Salary group (PE)
  2    AG      4       P               Year
  2    AH      8       P               Amount
  1    AI     20       A     MU        Skills (multiple-value)
```

## Descriptor Types

| Type | Description | Example |
|------|-------------|---------|
| Descriptor (DE) | Single-field inverted-list index | Employee ID |
| Superdescriptor | Combined from multiple fields/parts of fields | Last name + First name |
| Sub-descriptor | Portion of a field used as index | First 3 chars of name |
| Hyper descriptor | User-exit computed index | Soundex of name |
| Phonetic descriptor | Built-in phonetic index | Approximate name matching |
| Collation descriptor | Index with custom sort sequence | Locale-specific ordering |

### Superdescriptor Definition

```
ADACMP SUPERDE='S1=AE(1,4),AC(1,10)'
```
Creates superdescriptor S1 from bytes 1-4 of AE (department) and bytes 1-10 of AC (last name).

## ACB (ADABAS Control Block)

The ACB is the interface between the application program and ADABAS. Each DL/I-style
call fills in the ACB fields, then invokes the ADABAS nucleus.

### ACB Fields

| Field | Length | Description |
|-------|--------|-------------|
| Command code | 2 | Operation (L1, S1, A1, etc.) |
| Command ID | 4 | Identifies command sequence (for read-ahead, search save) |
| File number | 2 | Target file |
| Response code | 2 | Return status (0 = success) |
| ISN | 4 | Internal sequence number |
| ISN Lower Limit | 4 | Start ISN for range operations |
| ISN Quantity | 4 | Number of ISNs in ISN buffer |
| Format buffer length | 2 | Length of format buffer |
| Record buffer length | 2 | Length of record buffer |
| Search buffer length | 2 | Length of search buffer |
| Value buffer length | 2 | Length of value buffer |
| ISN buffer length | 2 | Length of ISN buffer |
| Addition 1 | 8 | Additional parameter (file/password for some commands) |
| Addition 2 | 4 | Length of compressed record, or other info |
| Addition 3 | 8 | Command time, or other info |
| Addition 4 | 8 | User area |

### Read Commands

| Command | Description |
|---------|-------------|
| L1 | Read by ISN (single record) |
| L2 | Read physical sequential |
| L3 | Read logical sequential (by descriptor value) |
| L4 | Read by ISN from ISN list (result of FIND) |
| L5 | Read physical sequential in descending order |
| L6 | Read logical sequential in descending order |
| L9 | Histogram (read inverted-list values without data records) |

### Search Commands

| Command | Description |
|---------|-------------|
| S1 | Find records matching search criteria |
| S2 | Find + sort result by descriptor |
| S4 | Find + sort by ISN |
| S8 | Process combined FIND results (AND/OR/NOT on saved ISN lists) |
| S9 | Sort saved ISN list by descriptor |

### Update Commands

| Command | Description |
|---------|-------------|
| A1 | Add (insert) a new record |
| N1 | Update record fields |
| N2 | Update record fields (extended -- add/delete MU/PE occurrences) |
| E1 | Delete a record |

### Session Commands

| Command | Description |
|---------|-------------|
| OP | Open user session (set options, assign user ID) |
| CL | Close user session |
| ET | End of transaction (commit) |
| BT | Backout transaction (rollback) |
| C1 | Begin sub-transaction |
| C2 | End sub-transaction |
| C3 | Backout sub-transaction |

### Common Response Codes

| Code | Meaning |
|------|---------|
| 0 | Success |
| 3 | End of file / no more records |
| 9 | Transaction aborted by nucleus |
| 17 | Invalid file number |
| 22 | Invalid command code |
| 34 | Invalid ISN |
| 48 | Security violation |
| 113 | Record too long for buffer |
| 145 | User not authorized |
| 148 | ADABAS nucleus not active |

## Buffer Types

ADABAS uses a set of buffers to communicate data between the application and the nucleus.

### Format Buffer (FB)

Specifies which fields to read or write, and their output format.

```
FB = 'AA,8,A,AC,20,A,AE,4,P.'
```

Format: `field-name,length,format` separated by commas, terminated by period.

### Record Buffer (RB)

Contains the actual data values in the layout specified by the format buffer. On read,
ADABAS fills this buffer; on write, the application fills it.

### Search Buffer (SB)

Specifies search criteria for FIND (S1/S2/S4) commands.

```
SB = 'AE,4,P,D.'
```

Operators: D (range/from-to), S (soft coupling), same field repeated for AND.

### Value Buffer (VB)

Contains the search values referenced by the search buffer.

```
VB = packed-value-for-AE
```

### ISN Buffer (IB)

Receives the list of ISNs matching a FIND command. Each ISN is a 4-byte binary value.

## COBOL ADABAS Call

```cobol
       CALL 'ADABAS' USING ACB-CONTROL-BLOCK
                            FORMAT-BUFFER
                            RECORD-BUFFER
                            SEARCH-BUFFER
                            VALUE-BUFFER
                            ISN-BUFFER.
```

## NATURAL Integration

ADABAS is most commonly programmed using Software AG's Natural 4GL, which provides
transparent access to ADABAS files through statements like:

```natural
READ EMPLOYEES BY NAME
  DISPLAY NAME SALARY DEPARTMENT
END-READ
```

Natural eliminates the need for explicit ACB manipulation, format/record buffers, and
low-level ADABAS commands in most application scenarios.

---
*Generated by Mainframe Code Wiki*
"#
    .to_string()
}

fn encoding_reference() -> String {
    r#"# Encoding Reference

Mainframe systems use EBCDIC (Extended Binary Coded Decimal Interchange Code) as their
native character encoding, in contrast to ASCII/UTF-8 used by distributed systems.
This page covers character encoding, decimal arithmetic formats, and binary representations
used in COBOL and other mainframe languages.

## EBCDIC Code Pages

EBCDIC uses 8 bits per character (256 code points). Different national variants are
defined as *code pages*. OpenMainframe supports 21 code pages:

| Code Page | Name/Region | Notable Differences from CP 037 |
|-----------|-------------|--------------------------------|
| 037 | USA / Canada | Base reference code page |
| 273 | Germany / Austria | Umlauts replace brackets/braces |
| 277 | Denmark / Norway | Nordic characters |
| 278 | Finland / Sweden | Nordic characters |
| 280 | Italy | Accented vowels |
| 284 | Spain / Latin America | Inverted punctuation |
| 285 | United Kingdom | Pound sign at x'5B' |
| 297 | France | Accented characters |
| 500 | International (Latin-1) | "International" EBCDIC, common for interchange |
| 871 | Iceland | Icelandic characters |
| 1047 | Latin-1 / Open Systems | C/POSIX compatible mapping, used by USS |
| 1140 | USA (Euro) | 037 + Euro sign at x'9F' |
| 1141 | Germany (Euro) | 273 + Euro sign |
| 1142 | Denmark/Norway (Euro) | 277 + Euro sign |
| 1143 | Finland/Sweden (Euro) | 278 + Euro sign |
| 1144 | Italy (Euro) | 280 + Euro sign |
| 1145 | Spain (Euro) | 284 + Euro sign |
| 1146 | UK (Euro) | 285 + Euro sign |
| 1147 | France (Euro) | 297 + Euro sign |
| 1148 | International (Euro) | 500 + Euro sign |
| 1149 | Iceland (Euro) | 871 + Euro sign |

## EBCDIC vs ASCII Collation

A critical difference: in EBCDIC, **letters sort before numbers**; in ASCII, **numbers
sort before letters**.

### EBCDIC Sort Order (CP 037)

```
Low values (x'00')
  ...
  Lowercase letters: a-z  (x'81'-x'A9')
  ...
  Uppercase letters: A-Z  (x'C1'-x'E9')
  ...
  Digits: 0-9  (x'F0'-x'F9')
  ...
High values (x'FF')
```

### ASCII Sort Order

```
Low values (x'00')
  ...
  Digits: 0-9  (x'30'-x'39')
  ...
  Uppercase letters: A-Z  (x'41'-x'5A')
  ...
  Lowercase letters: a-z  (x'61'-x'7A')
  ...
High values (x'FF')
```

### Common Character Mappings (CP 037)

| Character | EBCDIC Hex | ASCII Hex |
|-----------|-----------|-----------|
| Space | x'40' | x'20' |
| 0 | x'F0' | x'30' |
| A | x'C1' | x'41' |
| a | x'81' | x'61' |
| . (period) | x'4B' | x'2E' |
| , (comma) | x'6B' | x'2C' |
| + (plus) | x'4E' | x'2B' |
| - (minus) | x'60' | x'2D' |
| / (slash) | x'61' | x'2F' |
| = (equal) | x'7E' | x'3D' |
| LOW-VALUES | x'00' | x'00' |
| HIGH-VALUES | x'FF' | x'FF' |

## COMP-3 Packed Decimal

Packed decimal (COMP-3) stores two decimal digits per byte, with the last nibble
(half-byte) reserved for the sign.

### Format

```
PIC S9(5) COMP-3 value +12345:

Byte 1: 0x12    (digits 1, 2)
Byte 2: 0x34    (digits 3, 4)
Byte 3: 0x5C    (digit 5, sign C=positive)

Storage: 3 bytes for 5 digits
```

### Sign Nibble Values

| Nibble | Meaning |
|--------|---------|
| C | Positive (preferred) |
| A | Positive (alternate) |
| E | Positive (alternate) |
| F | Unsigned / positive |
| D | Negative (preferred) |
| B | Negative (alternate) |

### Storage Size Formula

```
Bytes = TRUNC((digits + 1) / 2) + (if (digits+1) is odd then 0 else 0)
      = FLOOR((digits / 2) + 1)

PIC S9(1) COMP-3  = 1 byte
PIC S9(3) COMP-3  = 2 bytes
PIC S9(5) COMP-3  = 3 bytes
PIC S9(7) COMP-3  = 4 bytes
PIC S9(9) COMP-3  = 5 bytes
PIC S9(13) COMP-3 = 7 bytes
PIC S9(15) COMP-3 = 8 bytes
PIC S9(17) COMP-3 = 9 bytes
PIC S9(18) COMP-3 = 10 bytes (maximum)
```

### Decimal Arithmetic

COBOL arithmetic on COMP-3 fields uses hardware decimal instructions:
- **AP** (Add Packed)
- **SP** (Subtract Packed)
- **MP** (Multiply Packed)
- **DP** (Divide Packed)
- **ZAP** (Zero and Add Packed)
- **CP** (Compare Packed)

A **S0C7 (Data Exception)** abend occurs if the packed field contains invalid data
(non-decimal nibbles in digit positions, or invalid sign nibble).

## Zoned Decimal

Zoned decimal stores one digit per byte. The zone nibble is x'F' for all bytes except
the last, where it contains the sign.

### Format

```
PIC S9(5) DISPLAY value +12345:

Byte 1: 0xF1    (zone F, digit 1)
Byte 2: 0xF2    (zone F, digit 2)
Byte 3: 0xF3    (zone F, digit 3)
Byte 4: 0xF4    (zone F, digit 4)
Byte 5: 0xC5    (sign C=positive, digit 5)

Storage: 5 bytes for 5 digits
```

### Sign Representation

| Configuration | Positive | Negative |
|---------------|----------|----------|
| Default (SIGN IS TRAILING) | Last byte zone = C | Last byte zone = D |
| SIGN IS LEADING | First byte zone = C | First byte zone = D |
| SIGN IS TRAILING SEPARATE | Append '+' (x'4E') | Append '-' (x'60') |
| SIGN IS LEADING SEPARATE | Prepend '+' (x'4E') | Prepend '-' (x'60') |

## Binary Formats

### COMP / BINARY

Standard mainframe binary uses big-endian byte order with a sign bit.

| PIC Clause | Bytes | Range |
|------------|-------|-------|
| S9(1) - S9(4) COMP | 2 | -9999 to +9999 (truncated to PIC) |
| S9(5) - S9(9) COMP | 4 | -999999999 to +999999999 |
| S9(10) - S9(18) COMP | 8 | -999999999999999999 to +999999999999999999 |

COMP fields are truncated to their PIC clause maximum, not the full binary range.

### COMP-5 (Native Binary)

COMP-5 uses the **full binary range** of the storage allocated, regardless of the PIC clause:

| PIC Clause | Bytes | Actual Range |
|------------|-------|-------------|
| S9(1) - S9(4) COMP-5 | 2 | -32768 to +32767 |
| S9(5) - S9(9) COMP-5 | 4 | -2,147,483,648 to +2,147,483,647 |
| S9(10) - S9(18) COMP-5 | 8 | Full 64-bit signed integer range |

COMP-5 is IBM-specific and corresponds to `int16_t`, `int32_t`, `int64_t`.

## Floating Point Formats

z/OS supports three floating-point formats:

### HFP (Hexadecimal Floating Point) -- IBM Traditional

| Type | COBOL | Bytes | Hex Digits | Decimal Digits |
|------|-------|-------|-----------|---------------|
| Short | COMP-1 | 4 | 6 | ~7 |
| Long | COMP-2 | 8 | 14 | ~16 |
| Extended | N/A | 16 | 28 | ~33 |

Format: `S EEEEEEE FFFFFFFFFFFFFFFFFFFFFFFF` (sign, 7-bit exponent base-16, fraction)

HFP radix is 16 (not 2), so each exponent increment shifts by 4 bits. This gives a wider
range but can lose precision for non-hex-aligned values.

### BFP (Binary Floating Point) -- IEEE 754

| Type | Bytes | Significand | Exponent Range |
|------|-------|-------------|----------------|
| Short | 4 | 23 bits (~7 decimal digits) | 10^-38 to 10^38 |
| Long | 8 | 52 bits (~15 decimal digits) | 10^-308 to 10^308 |
| Extended | 16 | 112 bits (~34 decimal digits) | 10^-4932 to 10^4932 |

BFP is the standard IEEE 754 binary format, fully compatible with distributed systems.

### DFP (Decimal Floating Point) -- IEEE 754-2008

| Type | Bytes | Decimal Digits | Exponent Range |
|------|-------|----------------|----------------|
| Short | 4 | 7 | 10^-101 to 10^96 |
| Long | 8 | 16 | 10^-398 to 10^369 |
| Extended | 16 | 34 | 10^-6176 to 10^6111 |

DFP stores decimal digits directly (no binary conversion), so `0.10` is exact.
This eliminates the decimal rounding issues inherent in BFP/HFP for financial calculations.

## PIC Clause Parsing Rules

The PIC (PICTURE) clause defines the external format of a data item.

### Symbol Reference

| Symbol | Meaning |
|--------|---------|
| 9 | Numeric digit |
| X | Any character |
| A | Alphabetic character |
| V | Implied decimal point |
| S | Sign (operational) |
| P | Assumed decimal scaling position |
| Z | Zero-suppressed digit |
| * | Check-protected digit |
| , | Insertion comma |
| . | Insertion decimal point |
| / | Insertion slash |
| 0 | Insertion zero |
| B | Insertion blank |
| + | Floating or fixed sign (positive/negative) |
| - | Floating or fixed sign (negative only) |
| CR | Credit symbol (2 chars, trailing) |
| DB | Debit symbol (2 chars, trailing) |
| $ | Currency symbol (floating or fixed) |

### Format String Examples

| PIC Clause | Category | Storage | Example Value |
|------------|----------|---------|--------------|
| PIC X(10) | Alphanumeric | 10 bytes | "HELLO     " |
| PIC 9(5) | Numeric display | 5 bytes | "00123" |
| PIC S9(5) | Signed numeric | 5 bytes | "0012C" (zoned, +123) |
| PIC S9(5)V99 | Decimal numeric | 7 bytes | "00123{" (zoned, +123.00) |
| PIC S9(5)V99 COMP-3 | Packed decimal | 5 bytes | 0x00123000C |
| PIC S9(9) COMP | Binary | 4 bytes | 0x0000007B (+123) |
| PIC Z,ZZ9.99 | Edited numeric | 8 bytes | "  123.00" |
| PIC $$$,$$9.99CR | Edited numeric | 13 bytes | "    $123.00  " |
| PIC 99/99/9999 | Edited date | 10 bytes | "03/15/2024" |

### Repetition Factor

`9(5)` is equivalent to `99999`. Applies to all PIC symbols:
- `X(80)` = 80 alphanumeric characters
- `Z(4)9` = four zero-suppressed digits + one always-displayed digit
- `9(5)V9(2)` = 5 integer digits, implied decimal, 2 fraction digits

---
*Generated by Mainframe Code Wiki*
"#
    .to_string()
}
