//! Unified data dictionary generator.

use std::fs;

use crate::{WikiConfig, WikiResult};

/// A single entry in the data dictionary.
#[derive(Debug, Clone)]
pub struct DataDictEntry {
    pub field_name: String,
    pub program: String,
    pub occurrences: usize,
}

/// Generate the data dictionary page.
pub fn generate_datadict_page(config: &WikiConfig, entries: &[DataDictEntry]) -> WikiResult<()> {
    let mut md = String::from("# Data Dictionary\n\n");
    md.push_str("Unified data dictionary of fields discovered across all analyzed programs.\n\n");

    if entries.is_empty() {
        md.push_str("*No data dictionary entries found.*\n");
    } else {
        md.push_str("| Field | Program | Occurrences |\n");
        md.push_str("|-------|---------|-------------|\n");
        for e in entries {
            md.push_str(&format!(
                "| {} | {} | {} |\n",
                e.field_name, e.program, e.occurrences
            ));
        }
    }

    md.push_str("\n---\n*Generated by Mainframe Code Wiki*\n");
    fs::write(config.output_dir.join("data/datadict.md"), md)?;
    Ok(())
}
