//! Language reference page generators for all 9 mainframe languages.

use std::fs;

use crate::{WikiConfig, WikiResult};

/// Generate all language reference pages.
pub fn generate_language_pages(config: &WikiConfig) -> WikiResult<()> {
    let out = &config.output_dir;
    fs::write(out.join("languages/index.md"), languages_index())?;
    fs::write(out.join("languages/cobol/index.md"), cobol_reference())?;
    fs::write(out.join("languages/jcl/index.md"), jcl_reference())?;
    fs::write(out.join("languages/rexx/index.md"), rexx_reference())?;
    fs::write(out.join("languages/hlasm/index.md"), hlasm_reference())?;
    fs::write(out.join("languages/pli/index.md"), pli_reference())?;
    fs::write(out.join("languages/clist/index.md"), clist_reference())?;
    fs::write(out.join("languages/easytrieve/index.md"), easytrieve_reference())?;
    fs::write(out.join("languages/natural/index.md"), natural_reference())?;
    fs::write(out.join("languages/focus/index.md"), focus_reference())?;
    Ok(())
}

fn languages_index() -> String {
    r#"# Mainframe Languages

This wiki documents all 9 mainframe programming languages supported by OpenMainframe.

## Language Comparison

| Language | Paradigm | Primary Use | Year | Crate |
|----------|----------|-------------|------|-------|
| [COBOL](cobol/index.md) | Procedural | Business applications | 1959 | `open-mainframe-cobol` |
| [JCL](jcl/index.md) | Declarative | Job control & batch | 1964 | `open-mainframe-jcl` |
| [REXX](rexx/index.md) | Interpreted | Scripting & automation | 1979 | `open-mainframe-rexx` |
| [HLASM](hlasm/index.md) | Assembly | System programming | 1966 | `open-mainframe-hlasm` |
| [PL/I](pli/index.md) | Multi-paradigm | Scientific & business | 1964 | `open-mainframe-pli` |
| [CLIST](clist/index.md) | Interpreted | TSO command scripts | 1966 | `open-mainframe-clist` |
| [Easytrieve](easytrieve/index.md) | 4GL | Reporting & file processing | 1970s | `open-mainframe-easytrieve` |
| [Natural](natural/index.md) | 4GL | ADABAS applications | 1979 | `open-mainframe-natural` |
| [FOCUS](focus/index.md) | 4GL | Reporting & analytics | 1975 | `open-mainframe-focus` |

## Language Overview

### COBOL
The dominant mainframe application language. OpenMainframe implements a full 8-pass compiler
supporting IBM Enterprise COBOL extensions, 77+ intrinsic functions, and JSON/XML processing.

### JCL
Job Control Language defines batch job execution on z/OS. The interpreter handles JOB, EXEC,
DD statements, PROC expansion, conditional processing, and utility program invocation.

### REXX
A powerful scripting language where everything is a string. Used extensively for TSO
automation, ISPF customization, and system administration. 70+ builtin functions.

### HLASM
High Level Assembler for direct hardware-level programming on System/390 and z/Architecture.
Supports macro language, conditional assembly, and structured programming extensions.

### PL/I
A multi-paradigm language combining features of COBOL, FORTRAN, and ALGOL. Rich data types,
exception handling via ON conditions, and both stream and record I/O.

### CLIST
Command List scripts for TSO automation. Simpler than REXX but still widely used for
interactive TSO applications and ISPF dialog customization.

### Easytrieve Plus
A 4GL optimized for report generation and file processing. Minimal coding required for
common batch operations like sorting, matching, and summarizing data.

### Natural
Software AG's 4GL designed for ADABAS database access. Features structured programming,
map-based screen handling, and deep integration with ADABAS inverted-list databases.

### FOCUS
Information Builders' 4GL for ad-hoc reporting, data analysis, and application development.
TABLE and GRAPH requests enable rapid report creation with minimal code.

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn cobol_reference() -> String {
    r#"# COBOL Language Reference

[Back to Languages](../index.md)

## Compilation Pipeline

OpenMainframe implements an 8-pass COBOL compiler:

| Pass | Name | Description |
|------|------|-------------|
| 0 | Options | Parse compiler option directives (`CBL`, `PROCESS`) |
| 1 | Conditional | Process conditional compilation (`>>IF`, `>>ELSE`, `>>END-IF`, `>>DEFINE`) |
| 2 | Copy | Expand `COPY` statements, resolve copybook libraries |
| 3 | Replace | Apply `REPLACE` directives and `REPLACING` phrases |
| 4 | Lexer | Tokenize source into COBOL tokens |
| 5 | Parser | Build AST from token stream |
| 6 | Semantic | Type checking, scope resolution, data item layout |
| 7 | Codegen | Generate executable representation (optional LLVM backend) |

## Source Formats

| Format | Sequence (1-6) | Indicator (7) | Area A (8-11) | Area B (12-72) | Comment (73-80) |
|--------|----------------|---------------|---------------|----------------|-----------------|
| Fixed | Sequence numbers | `*`, `/`, `D`, `-` | Division/section/paragraph headers, 01/77 levels | Statements | Identification |
| Free | N/A | N/A | N/A | Entire line | `*>` inline |

## Divisions

### IDENTIFICATION DIVISION
Required. Contains `PROGRAM-ID`, `AUTHOR`, `DATE-WRITTEN`, `DATE-COMPILED`, `SECURITY`.

### ENVIRONMENT DIVISION
- **CONFIGURATION SECTION**: `SOURCE-COMPUTER`, `OBJECT-COMPUTER`, `SPECIAL-NAMES`
- **INPUT-OUTPUT SECTION**: `FILE-CONTROL` (SELECT/ASSIGN), `I-O-CONTROL`

### DATA DIVISION
- **FILE SECTION**: FD/SD entries for file records
- **WORKING-STORAGE SECTION**: Program-lifetime variables
- **LOCAL-STORAGE SECTION**: Invocation-scoped variables (allocated per CALL)
- **LINKAGE SECTION**: Parameters received via CALL USING
- **REPORT SECTION**: Report Writer (RD entries)
- **SCREEN SECTION**: Screen description entries

### PROCEDURE DIVISION
Contains executable statements organized in sections and paragraphs.

## Data Types

### PIC Clause Patterns

| Symbol | Meaning | Example |
|--------|---------|---------|
| `9` | Numeric digit | `PIC 9(5)` = 5-digit number |
| `X` | Alphanumeric | `PIC X(20)` = 20-char string |
| `A` | Alphabetic | `PIC A(10)` = 10-letter string |
| `V` | Implied decimal | `PIC 9(3)V99` = 3.2 digits |
| `S` | Sign | `PIC S9(4)` = signed number |
| `P` | Scaling position | `PIC PPP9` = 0.0009 scale |
| `Z` | Zero-suppressed | `PIC Z(4)9` = suppress leading zeros |
| `*` | Check-protect | `PIC **(4)9` = fill with asterisks |
| `.` | Decimal point | `PIC 9(3).99` = inserted decimal |
| `,` | Comma insert | `PIC 9,999` = inserted comma |
| `$` | Currency | `PIC $$,$$9.99` = floating dollar |
| `+` / `-` | Sign edit | `PIC +(4)9` = floating plus sign |
| `CR` / `DB` | Credit/Debit | `PIC 9(5)CR` = trailing credit |

### USAGE Types

| USAGE | Storage | Description |
|-------|---------|-------------|
| `DISPLAY` | EBCDIC zoned decimal | Default, one byte per digit |
| `COMP` / `COMP-4` / `BINARY` | Binary integer | 2, 4, or 8 bytes |
| `COMP-3` / `PACKED-DECIMAL` | Packed decimal | 2 digits per byte + sign nibble |
| `COMP-5` / `NATIVE BINARY` | Native binary | Platform-native byte order |
| `COMP-1` | Single-precision float | 4 bytes IEEE/hex float |
| `COMP-2` | Double-precision float | 8 bytes IEEE/hex float |
| `POINTER` | Address | 4 or 8 bytes |
| `INDEX` | Index value | Internal index representation |

## Intrinsic Functions (77+)

### Numeric Functions
`ABS`, `ACOS`, `ANNUITY`, `ASIN`, `ATAN`, `COS`, `FACTORIAL`, `INTEGER`,
`INTEGER-OF-DATE`, `INTEGER-OF-DAY`, `INTEGER-PART`, `LOG`, `LOG10`, `MAX`,
`MEAN`, `MEDIAN`, `MIDRANGE`, `MIN`, `MOD`, `NUMVAL`, `NUMVAL-C`, `ORD`,
`ORD-MAX`, `ORD-MIN`, `PRESENT-VALUE`, `RANDOM`, `RANGE`, `REM`, `SIGN`,
`SIN`, `SQRT`, `STANDARD-DEVIATION`, `SUM`, `TAN`, `VARIANCE`

### String Functions
`CHAR`, `COMBINED-DATETIME`, `CONCATENATE`, `DISPLAY-OF`, `LENGTH`, `LOWER-CASE`,
`NATIONAL-OF`, `REVERSE`, `SUBSTITUTE`, `TRIM`, `UPPER-CASE`, `ULENGTH`,
`UPOS`, `USUBSTR`, `UWIDTH`

### Date/Time Functions
`CURRENT-DATE`, `DATE-OF-INTEGER`, `DATE-TO-YYYYMMDD`, `DAY-OF-INTEGER`,
`DAY-TO-YYYYDDD`, `FORMATTED-CURRENT-DATE`, `FORMATTED-DATE`, `FORMATTED-DATETIME`,
`FORMATTED-TIME`, `INTEGER-OF-DATE`, `INTEGER-OF-DAY`, `INTEGER-OF-FORMATTED-DATE`,
`SECONDS-FROM-FORMATTED-TIME`, `SECONDS-PAST-MIDNIGHT`, `TEST-DATE-YYYYMMDD`,
`TEST-DAY-YYYYDDD`, `TEST-FORMATTED-DATETIME`, `WHEN-COMPILED`, `YEAR-TO-YYYY`

### Financial Functions
`ANNUITY`, `PRESENT-VALUE`

### General Functions
`BYTE-LENGTH`, `E`, `EXCEPTION-FILE`, `EXCEPTION-LOCATION`, `EXCEPTION-STATEMENT`,
`EXCEPTION-STATUS`, `HEX-OF`, `HEX-TO-CHAR`, `LOCALE-COMPARE`, `LOCALE-DATE`,
`LOCALE-TIME`, `LOCALE-TIME-FROM-SECONDS`, `MODULE-CALLER-ID`, `MODULE-DATE`,
`MODULE-FORMATTED-DATE`, `MODULE-ID`, `MODULE-NAME`, `MODULE-PATH`, `MODULE-SOURCE`,
`MODULE-TIME`, `PI`, `TEST-NUMVAL`, `TEST-NUMVAL-C`, `TEST-NUMVAL-F`

## Compiler Options

| Option | Description | Default |
|--------|-------------|---------|
| `APOST` / `QUOTE` | Literal delimiter | `QUOTE` |
| `ARITH(COMPAT)` / `ARITH(EXTEND)` | Arithmetic precision (18 vs 31 digits) | `COMPAT` |
| `CODEPAGE(ccsid)` | EBCDIC code page | 1140 |
| `DBCS` / `NODBCS` | Double-byte character support | `NODBCS` |
| `LIB` / `NOLIB` | COPY statement processing | `LIB` |
| `NUMPROC(NOPFD)` / `NUMPROC(PFD)` | Sign fixup on numeric input | `NOPFD` |
| `TRUNC(STD)` / `TRUNC(OPT)` / `TRUNC(BIN)` | Binary truncation rules | `STD` |
| `SQLCCSID` / `NOSQLCCSID` | SQL string encoding | `NOSQLCCSID` |
| `INTDATE(ANSI)` / `INTDATE(LILIAN)` | Date integer base | `ANSI` |

## IBM Enterprise COBOL Extensions

- `JSON GENERATE` / `JSON PARSE` (COBOL-2014)
- `XML GENERATE` / `XML PARSE`
- `FUNCTION ULENGTH`, `UPOS`, `USUBSTR`, `UWIDTH` (Unicode)
- `DISPLAY-OF` / `NATIONAL-OF` (encoding conversion)
- `UTF-8` data item support
- `VOLATILE` clause
- Floating-point USAGE types (`COMP-1`, `COMP-2`)
- 31-digit precision with `ARITH(EXTEND)`

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn jcl_reference() -> String {
    r#"# JCL Language Reference

[Back to Languages](../index.md)

## Statement Types

| Statement | Syntax | Purpose |
|-----------|--------|---------|
| `JOB` | `//jobname JOB ...` | Define a job, accounting, class, priority |
| `EXEC` | `//stepname EXEC PGM=prog` | Execute a program or procedure |
| `DD` | `//ddname DD ...` | Define a data definition (file, dataset, sysout) |
| `PROC` | `//procname PROC ...` | Begin a cataloged or in-stream procedure |
| `PEND` | `// PEND` | End an in-stream procedure |
| `IF/THEN/ELSE/ENDIF` | `// IF (cond) THEN` | Conditional step execution |
| `INCLUDE` | `// INCLUDE MEMBER=name` | Include a JCL member from a PDS |
| `JCLLIB` | `// JCLLIB ORDER=(libs)` | Specify procedure library search order |
| `SET` | `// SET VAR=value` | Set symbolic variable value |
| `COMMAND` | `// COMMAND 'cmd'` | Issue operator command |
| `OUTPUT` | `//name OUTPUT ...` | Define output descriptors for SYSOUT |
| `/*` | `/*` | Delimiter (end of in-stream data) |
| `//*` | `//*` | Comment |

## DD Statement Parameters

### Dataset Identification

| Parameter | Syntax | Description |
|-----------|--------|-------------|
| `DSN` / `DSNAME` | `DSN=MY.DATASET` | Dataset name |
| | `DSN=MY.DATASET(MBR)` | PDS member |
| | `DSN=&&TEMP` | Temporary dataset |
| | `DSN=*.stepname.ddname` | Backward reference |
| `DISP` | `DISP=(status,normal,abnormal)` | Disposition |
| | Status: `NEW`, `OLD`, `SHR`, `MOD` | Initial status |
| | Normal: `DELETE`, `KEEP`, `PASS`, `CATLG`, `UNCATLG` | Normal termination |
| | Abnormal: `DELETE`, `KEEP`, `CATLG`, `UNCATLG` | Abnormal termination |

### Space Allocation

| Parameter | Syntax | Description |
|-----------|--------|-------------|
| `SPACE` | `SPACE=(unit,(primary,secondary,directory))` | Allocate space |
| | Unit: `TRK`, `CYL`, `blksize` | Allocation unit |
| `AVGREC` | `AVGREC=U\|K\|M` | Average record count multiplier |

### Data Control Block (DCB)

| Subparameter | Values | Description |
|--------------|--------|-------------|
| `RECFM` | `F`, `FB`, `V`, `VB`, `FBA`, `VBA`, `U` | Record format |
| `LRECL` | integer | Logical record length |
| `BLKSIZE` | integer | Block size |
| `DSORG` | `PS`, `PO`, `DA`, `IS` | Dataset organization |
| `KEYLEN` | integer | Key length (VSAM/ISAM) |
| `RKP` | integer | Relative key position |

### Other DD Parameters

| Parameter | Description |
|-----------|-------------|
| `UNIT` | Device type (`SYSDA`, `TAPE`, `3390`) |
| `VOL=SER=volser` | Volume serial number |
| `SYSOUT=class` | Output class (A=print, *=same as MSGCLASS) |
| `DUMMY` | Null file (discard output, EOF on input) |
| `*` | In-stream data follows |
| `DATA` | In-stream data with JCL statements |
| `LIKE` | Copy attributes from a model dataset |
| `REFDD` | Reference another DD for attributes |
| `LABEL` | Tape label type and sequence |
| `EXPDT` / `RETPD` | Expiration date / retention period |

## PROC Parameters and Symbolic Substitution

```
//MYPROC PROC REGION=4M,DSN=MY.DEFAULT
//STEP1  EXEC PGM=MYPROG
//INPUT  DD   DSN=&DSN,DISP=SHR
//       EXEC MYPROC,DSN=MY.OVERRIDE,REGION=8M
```

- Symbolic parameters are prefixed with `&`
- Default values specified on `PROC` statement
- Override values specified on `EXEC` statement
- `SET` statement can assign values outside procedures

## Condition Code Processing

### COND Parameter (Legacy)
```
//STEP2 EXEC PGM=PROG2,COND=(4,LT)
```
Skip step if ANY prior return code is less than 4. Operators: `GT`, `GE`, `EQ`, `NE`, `LT`, `LE`.

### IF/THEN/ELSE/ENDIF (Preferred)
```
// IF (STEP1.RC = 0) THEN
//STEP2 EXEC PGM=PROG2
// ELSE
//STEP3 EXEC PGM=ERRRPT
// ENDIF
```

Supported comparisons: `RC`, `ABENDCC`, `ABEND`, `RUN`, `stepname.RC`, `stepname.procstep.RC`.
Logical operators: `AND` (`&`), `OR` (`|`), `NOT`.

## Return Codes

| Code | Meaning |
|------|---------|
| 0 | Successful |
| 4 | Warning |
| 8 | Error |
| 12 | Severe error |
| 16 | Terminal error |

## GDG Relative Generation References

| Reference | Meaning |
|-----------|---------|
| `MY.GDG(0)` | Current generation |
| `MY.GDG(+1)` | Next (new) generation |
| `MY.GDG(-1)` | Previous generation |

## Utility Program Patterns

| Utility | Purpose | Key DD Names |
|---------|---------|-------------|
| `IEBCOPY` | Copy/merge PDS members | `SYSUT1` (input), `SYSUT2` (output), `SYSIN` (control) |
| `IEBGENER` | Copy sequential dataset | `SYSUT1` (input), `SYSUT2` (output), `SYSIN` (control) |
| `IDCAMS` | VSAM catalog services | `SYSIN` (commands), `SYSPRINT` (output) |
| `IEFBR14` | No-op (allocate/delete only) | DD statements trigger allocation |
| `SORT` | Sort/merge records | `SORTIN`, `SORTOUT`, `SYSIN` |
| `IKJEFT01` | TSO-in-batch | `SYSTSIN` (commands), `SYSTSPRT` (output) |
| `IRXJCL` | REXX-in-batch | `SYSTSIN`, `SYSTSPRT`, `SYSEXEC` |

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn rexx_reference() -> String {
    r#"# REXX Language Reference

[Back to Languages](../index.md)

## Overview

REXX (Restructured Extended Executor) is an interpreted scripting language where
**every value is a string**. Numbers are strings that happen to look numeric.
Arithmetic is performed on string representations with arbitrary precision.

## Value Model

- All values are character strings
- Numbers are strings matching a numeric pattern (optional sign, digits, optional decimal, optional exponent)
- Arithmetic precision controlled by `NUMERIC DIGITS` (default 9)
- Comparison: strict (`==`, `\==`, `>>`, `<<`) vs. normal (`=`, `\=`, `>`, `<`)

## Control Flow

### DO/END
```rexx
DO i = 1 TO 10 BY 2        /* counted */
DO WHILE condition          /* pre-test */
DO UNTIL condition          /* post-test */
DO FOREVER                  /* infinite */
DO 5                        /* simple repeat */
```

### IF/THEN/ELSE
```rexx
IF condition THEN
  instruction
ELSE
  instruction
```

### SELECT/WHEN/OTHERWISE
```rexx
SELECT
  WHEN cond1 THEN instr1
  WHEN cond2 THEN instr2
  OTHERWISE instrn
END
```

### Loop Control
- `ITERATE` - skip to next iteration (like `continue`)
- `LEAVE` - exit loop (like `break`)
- `ITERATE name` / `LEAVE name` - target a named DO loop

## PARSE Instruction

| Variant | Source |
|---------|--------|
| `PARSE ARG` | Argument string |
| `PARSE PULL` | Data stack or terminal (uppercase) |
| `PARSE VAR name` | Named variable |
| `PARSE VALUE expr WITH` | Expression result |
| `PARSE SOURCE` | Program invocation info |
| `PARSE VERSION` | Interpreter version |
| `PARSE NUMERIC` | Current NUMERIC settings |
| `PARSE LINEIN` | Terminal input (no stack) |

Template patterns: literal delimiters, positional (absolute `=n`, relative `+n`/`-n`), variable.

## Builtin Functions (70+)

### String Functions
`ABBREV`, `CENTER`/`CENTRE`, `CHANGESTR`, `COMPARE`, `COPIES`, `COUNTSTR`,
`DELSTR`, `INSERT`, `LASTPOS`, `LEFT`, `LENGTH`, `OVERLAY`, `POS`,
`REVERSE`, `RIGHT`, `SPACE`, `STRIP`, `SUBSTR`, `SUBWORD`, `TRANSLATE`,
`VERIFY`, `WORDINDEX`, `WORDLENGTH`, `WORDPOS`, `WORDS`

### Word Functions
`DELWORD`, `SUBWORD`, `WORD`, `WORDINDEX`, `WORDLENGTH`, `WORDPOS`, `WORDS`

### Numeric Functions
`ABS`, `FORMAT`, `MAX`, `MIN`, `RANDOM`, `SIGN`, `TRUNC`

### Conversion Functions
`B2X`, `C2D`, `C2X`, `D2C`, `D2X`, `X2B`, `X2C`, `X2D`

### Bit/Logical Functions
`BITAND`, `BITOR`, `BITXOR`

### I/O Functions
`CHARIN`, `CHAROUT`, `CHARS`, `LINEIN`, `LINEOUT`, `LINES`, `STREAM`

### Comparison/Information
`DATATYPE`, `DIGITS`, `FORM`, `FUZZ`, `QUEUED`, `SOURCELINE`, `SYMBOL`,
`TRACE`, `VALUE`, `ADDRESS`, `ARG`, `CONDITION`, `DATE`, `ERRORTEXT`, `TIME`

## Stem Variables and Compound Variables

```rexx
stem.        = ''      /* set default value */
stem.1       = 'first'
stem.2       = 'second'
stem.0       = 2       /* conventional count */
stem.key     = 'value' /* associative array */
stem.i.j     = 'grid'  /* multi-dimensional */
```

Tail components are uppercased and concatenated with dots. The value of `stem.expr`
uses the current value of `expr` as the tail.

## Host Command Environments

| Environment | Purpose | Example |
|-------------|---------|---------|
| `TSO` | TSO commands (default in TSO) | `ADDRESS TSO "ALLOC FI(IN) DA('MY.DATA') SHR"` |
| `MVS` | MVS system commands | `ADDRESS MVS "EXECIO * DISKR mydd (STEM line. FINIS"` |
| `ISPEXEC` | ISPF dialog services | `ADDRESS ISPEXEC "DISPLAY PANEL(MYPANEL)"` |
| `ISREDIT` | ISPF editor macros | `ADDRESS ISREDIT "(LINE) = LINE .ZCSR"` |
| `CONSOLE` | MVS console commands | `ADDRESS CONSOLE "D A,L"` |
| `LINK` / `LINKMVS` | Call load modules | `ADDRESS LINKMVS "MYPROG parms"` |

## SIGNAL ON (Exception Handling)

| Condition | Triggered By |
|-----------|-------------|
| `ERROR` | Host command returns non-zero RC |
| `FAILURE` | Host command fails completely |
| `HALT` | External interrupt |
| `NOVALUE` | Uninitialized variable referenced |
| `SYNTAX` | Syntax or runtime error |
| `NOTREADY` | I/O not ready |

```rexx
SIGNAL ON NOVALUE NAME trap_novalue
SIGNAL ON SYNTAX NAME trap_syntax
```

Special variables set on trap: `SIGL` (line number), `RC` (return code).
`CONDITION('C')` returns condition name, `CONDITION('D')` returns description.

## Numeric Settings

```rexx
NUMERIC DIGITS 15      /* precision (default 9) */
NUMERIC FUZZ 2          /* digits ignored in comparison */
NUMERIC FORM SCIENTIFIC /* exponential notation (default) */
NUMERIC FORM ENGINEERING
```

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn hlasm_reference() -> String {
    r#"# HLASM Language Reference

[Back to Languages](../index.md)

## Overview

High Level Assembler (HLASM) is the z/Architecture assembler providing direct access to
machine instructions, macro facilities, and conditional assembly.

## Instruction Formats

| Format | Operands | Length | Example |
|--------|----------|--------|---------|
| RR | R1,R2 | 2 | `LR 5,6` |
| RX | R1,D2(X2,B2) | 4 | `L 5,=F'100'` |
| RS | R1,R3,D2(B2) | 4 | `LM 14,12,12(13)` |
| SI | D1(B1),I2 | 4 | `CLI 0(5),C'A'` |
| SS | D1(L1,B1),D2(L2,B2) | 6 | `MVC 0(80,7),0(8)` |
| S | D2(B2) | 4 | `LPSW 0(3)` |
| RRE | R1,R2 | 4 | `MSR 5,6` |
| RIL | R1,I2/RI2 | 6 | `BRCL 15,target` |
| RI | R1,I2 | 4 | `AHI 5,100` |
| RXY | R1,D2(X2,B2) | 6 | `LY 5,4096(,12)` |
| RSY | R1,R3,D2(B2) | 6 | `STMG 14,12,8(13)` |
| SIY | D1(B1),I2 | 6 | `CLIY 4096(5),C'A'` |
| SSE | D1(B1),D2(B2) | 6 | `LASP 0(1),0(2)` |

## Key Machine Instructions

### Data Movement
| Instruction | Format | Description |
|-------------|--------|-------------|
| `L` | RX | Load fullword from memory |
| `ST` | RX | Store fullword to memory |
| `LR` | RR | Load register (copy register) |
| `LA` | RX | Load address |
| `LH` / `STH` | RX | Load/store halfword |
| `LM` / `STM` | RS | Load/store multiple registers |
| `MVC` | SS | Move characters (up to 256 bytes) |
| `MVI` | SI | Move immediate byte |
| `MVCL` | RR | Move character long |
| `XC` | SS | Exclusive OR characters (used to clear) |
| `ICM` / `STCM` | RS | Insert/store characters under mask |

### Arithmetic
| Instruction | Format | Description |
|-------------|--------|-------------|
| `A` / `AR` | RX/RR | Add fullword |
| `S` / `SR` | RX/RR | Subtract fullword |
| `M` / `MR` | RX/RR | Multiply (even-odd pair) |
| `D` / `DR` | RX/RR | Divide (even-odd pair) |
| `AH` / `SH` | RX | Add/subtract halfword |
| `AP` / `SP` | SS | Add/subtract packed decimal |
| `MP` / `DP` | SS | Multiply/divide packed decimal |
| `ZAP` | SS | Zero and add packed |
| `CVB` / `CVD` | RX | Convert binary/decimal |

### Comparison
| Instruction | Format | Description |
|-------------|--------|-------------|
| `C` / `CR` | RX/RR | Compare fullword |
| `CH` | RX | Compare halfword |
| `CL` / `CLR` | RX/RR | Compare logical (unsigned) |
| `CLC` | SS | Compare logical characters |
| `CLI` | SI | Compare logical immediate |
| `CP` | SS | Compare packed decimal |
| `TM` | SI | Test under mask |

### Branching
| Instruction | Format | Description |
|-------------|--------|-------------|
| `BC` | RX | Branch on condition |
| `BCR` | RR | Branch on condition register |
| `BAL` / `BALR` | RX/RR | Branch and link |
| `BAS` / `BASR` | RX/RR | Branch and save |
| `BCT` / `BCTR` | RX/RR | Branch on count |
| `BXH` / `BXLE` | RS | Branch on index high/low-equal |

Extended mnemonics: `B` (unconditional), `BE`/`BNE`, `BH`/`BNH`, `BL`/`BNL`,
`BZ`/`BNZ`, `BO`/`BNO`, `BP`/`BNP`, `BM`/`BNM`.

### I/O (Channel)
| Instruction | Description |
|-------------|-------------|
| `SIO` / `SIOF` | Start I/O / Start I/O Fast |
| `TIO` | Test I/O |
| `HIO` | Halt I/O |
| `SSCH` | Start Subchannel |
| `TSCH` | Test Subchannel |

## Assembler Directives

| Directive | Syntax | Description |
|-----------|--------|-------------|
| `DC` | `DC type'value'` | Define constant (`F`, `H`, `A`, `V`, `C`, `X`, `P`, `Z`, `D`, `E`) |
| `DS` | `DS type` | Define storage (reserve space) |
| `EQU` | `name EQU value` | Equate symbol to value |
| `USING` | `USING base,reg` | Establish base register addressability |
| `DROP` | `DROP reg` | Drop base register |
| `CSECT` | `name CSECT` | Start control section |
| `DSECT` | `name DSECT` | Start dummy section (like a struct) |
| `ENTRY` | `ENTRY name` | External entry point |
| `EXTRN` | `EXTRN name` | External reference |
| `LTORG` | `LTORG` | Flush literal pool |
| `ORG` | `ORG expr` | Set location counter |
| `COPY` | `COPY member` | Copy source member |
| `END` | `END [entry]` | End of assembly |
| `PRINT` | `PRINT ON/OFF/GEN/NOGEN` | Listing control |

## Macro Language

### Defining a Macro
```hlasm
         MACRO
&LABEL   MYMACRO &PARM1,&PARM2,&KEY=DEFAULT
         AIF ('&PARM1' EQ '').NOPARM
&LABEL   L     5,&PARM1
         ST    5,&PARM2
         AGO   .DONE
.NOPARM  ANOP
         SR    5,5
.DONE    MEND
```

### Key Macro Features
- `&SYSLIST` - positional parameter array
- `&SYSNDX` - unique suffix counter for generated labels
- `&SYSDATE`, `&SYSTIME`, `&SYSPARM` - system variables
- `&IF`/`&ELSE`/`&ENDIF` - conditional assembly (AIF/AGO)
- `GBLA`/`GBLB`/`GBLC` - global SET symbols (arithmetic/boolean/character)
- `LCLA`/`LCLB`/`LCLC` - local SET symbols
- `SETA`/`SETB`/`SETC` - assign SET symbols
- `MNOTE` - generate assembly-time message
- `MEXIT` - exit macro early
- `AREAD` - read source line during macro expansion

### Conditional Assembly
```hlasm
         AIF   ('&TYPE' EQ 'FULL').FULL
         AIF   ('&TYPE' EQ 'HALF').HALF
         AGO   .DEFAULT
.FULL    ANOP
         DS    F
         AGO   .DONE
.HALF    ANOP
         DS    H
.DEFAULT ANOP
         DS    CL1
.DONE    ANOP
```

## Object Module Format

| Record Type | Content |
|-------------|---------|
| ESD | External Symbol Dictionary (CSECTs, ENTRYs, EXTRNs) |
| TXT | Object code (instructions and data) |
| RLD | Relocation Dictionary (address constants) |
| END | End of module, optional entry point |
| SYM | Symbol table (optional, for debugging) |

## Linkage Conventions (z/OS)

Standard linkage:
- R1 = parameter list address
- R13 = save area address
- R14 = return address
- R15 = entry point address / return code
- Save area: 18 fullwords (72 bytes), chained via words 2 (backward) and 3 (forward)

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn pli_reference() -> String {
    r#"# PL/I Language Reference

[Back to Languages](../index.md)

## Overview

PL/I (Programming Language One) is a multi-paradigm language combining features of COBOL
(business), FORTRAN (scientific), and ALGOL (structured programming). It offers rich data
types, exception handling, and both record and stream I/O.

## Data Types (11 Categories)

### Arithmetic Types

| Type | Syntax | Description |
|------|--------|-------------|
| `FIXED DECIMAL` | `DCL x FIXED DEC(7,2)` | Packed decimal, precision (p,q) |
| `FIXED BINARY` | `DCL x FIXED BIN(31)` | Binary integer, precision p |
| `FLOAT DECIMAL` | `DCL x FLOAT DEC(6)` | Floating-point, decimal precision |
| `FLOAT BINARY` | `DCL x FLOAT BIN(53)` | Floating-point, binary precision |

### String Types

| Type | Syntax | Description |
|------|--------|-------------|
| `CHARACTER` | `DCL x CHAR(20)` | Fixed-length character string |
| `CHARACTER VARYING` | `DCL x CHAR(100) VAR` | Variable-length string |
| `BIT` | `DCL x BIT(8)` | Bit string |
| `BIT VARYING` | `DCL x BIT(32) VAR` | Variable-length bit string |
| `PICTURE` | `DCL x PIC '999V99'` | Edited numeric/character |
| `GRAPHIC` | `DCL x GRAPHIC(10)` | DBCS string |
| `WIDECHAR` | `DCL x WIDECHAR(10)` | Unicode string |

### Special Types

| Type | Syntax | Description |
|------|--------|-------------|
| `POINTER` | `DCL p POINTER` | Memory address |
| `OFFSET` | `DCL o OFFSET(area)` | Offset within an area |
| `AREA` | `DCL a AREA(1000)` | Heap region for ALLOCATE |
| `FILE` | `DCL f FILE` | File variable |
| `ENTRY` | `DCL e ENTRY(FIXED BIN) RETURNS(FIXED BIN)` | Procedure entry point |
| `LABEL` | `DCL l LABEL` | Statement label variable |
| `FORMAT` | `DCL fmt FORMAT` | Format item list variable |

## Storage Classes

| Class | Description |
|-------|-------------|
| `AUTOMATIC` | Stack-allocated (default for internal procedures) |
| `STATIC` | Persists for program duration |
| `CONTROLLED` | Stack of allocations (ALLOCATE/FREE) |
| `BASED` | Pointer-addressed storage |
| `DEFINED` | Overlays another variable |
| `PARAMETER` | Procedure argument |

## Exception Handling: ON Conditions

| Condition | Triggered By |
|-----------|-------------|
| `CONVERSION` | Invalid data conversion |
| `ENDFILE(file)` | End of file reached |
| `ENDPAGE(file)` | End of page in print file |
| `ERROR` | Any unhandled condition |
| `FINISH` | Program termination |
| `FIXEDOVERFLOW` | Fixed-point overflow |
| `OVERFLOW` | Float overflow |
| `UNDERFLOW` | Float underflow |
| `ZERODIVIDE` | Division by zero |
| `KEY(file)` | Record key error |
| `NAME(file)` | Invalid data-directed name |
| `RECORD(file)` | Record I/O error |
| `TRANSMIT(file)` | I/O transmission error |
| `UNDEFINEDFILE(file)` | File open failed |
| `STRINGRANGE` | Substring out of bounds |
| `STRINGSIZE` | String truncation |
| `SUBSCRIPTRANGE` | Array index out of bounds |
| `SIZE` | Numeric truncation |
| `AREA` | Area overflow |
| `ATTENTION` | Terminal interrupt |
| `CONDITION(name)` | User-defined condition |
| `STORAGE` | Storage allocation failed |

```pli
ON ENDFILE(INFILE) EOF = '1'B;
ON CONVERSION BEGIN;
  PUT SKIP LIST('Bad data: ' || ONSOURCE());
  ONSOURCE() = '0';
END;
```

## I/O Statements

### Record I/O (Files)
| Statement | Description |
|-----------|-------------|
| `OPEN FILE(f) INPUT/OUTPUT/UPDATE` | Open a file |
| `CLOSE FILE(f)` | Close a file |
| `READ FILE(f) INTO(var)` | Read sequential record |
| `READ FILE(f) INTO(var) KEY(key)` | Read by key (VSAM) |
| `WRITE FILE(f) FROM(var)` | Write record |
| `REWRITE FILE(f) FROM(var)` | Update in place |
| `DELETE FILE(f)` | Delete record |

### Stream I/O
| Statement | Description |
|-----------|-------------|
| `GET LIST(vars)` | List-directed input |
| `GET EDIT(vars)(formats)` | Edit-directed input |
| `GET DATA(vars)` | Data-directed input |
| `PUT LIST(exprs)` | List-directed output |
| `PUT EDIT(exprs)(formats)` | Edit-directed output |
| `PUT DATA(vars)` | Data-directed output |

### Format Items
`A(w)` (character), `F(w,d)` (fixed-point), `E(w,d)` (float), `B(w)` (bit),
`P'picture'` (picture), `COLUMN(n)`, `LINE(n)`, `PAGE`, `SKIP(n)`, `X(n)` (spacing).

## ALLOCATE/FREE (Controlled Storage)

```pli
DCL stack FIXED BIN(31) CONTROLLED;
ALLOCATE stack;       /* push allocation */
stack = 42;
ALLOCATE stack;       /* another push */
stack = 99;
FREE stack;           /* pop to previous */
/* stack is now 42 */
```

## Built-in Functions (50+ Key)

### String Functions
`LENGTH`, `SUBSTR`, `INDEX`, `VERIFY`, `TRANSLATE`, `TRIM`, `LEFT`, `RIGHT`,
`CENTER`, `COPY`, `REVERSE`, `SEARCH`, `SEARCHR`, `TALLY`, `REPEAT`,
`HIGH`, `LOW`, `CHAR`, `BIT`, `COLLATE`, `LOWERCASE`, `UPPERCASE`

### Arithmetic Functions
`ABS`, `CEIL`, `FLOOR`, `MAX`, `MIN`, `MOD`, `ROUND`, `SIGN`, `TRUNC`,
`SQRT`, `LOG`, `LOG2`, `LOG10`, `EXP`, `SIN`, `COS`, `TAN`, `ATAN`, `ATAND`

### Array Functions
`DIM`, `HBOUND`, `LBOUND`, `SUM`, `PROD`, `POLY`

### Storage Functions
`ADDR`, `NULL`, `ALLOCATION`, `CURRENTSTORAGE`, `STORAGE`, `SIZE`,
`SYSNULL`, `PTRADD`, `PTRDIFF`, `OFFSETADD`, `OFFSETDIFF`

### Condition Functions
`ONCODE`, `ONFILE`, `ONKEY`, `ONSOURCE`, `ONCHAR`, `ONLOC`, `DATAFIELD`

### Date/Time
`DATE`, `TIME`, `DATETIME`, `DAYS`, `DAYSTODATE`, `DAYSMICRO`,
`SECS`, `SECSTODATE`, `SECSMICRO`

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn clist_reference() -> String {
    r#"# CLIST Language Reference

[Back to Languages](../index.md)

## Overview

CLIST (Command List) is an interpretive command language for TSO/E. CLISTs automate
sequences of TSO commands and can build interactive applications using ISPF services.

## Commands

### Variable and I/O Commands

| Command | Syntax | Description |
|---------|--------|-------------|
| `SET` | `SET &VAR = expr` | Assign a value to a variable |
| `WRITE` | `WRITE text` | Display a line to the terminal |
| `WRITENR` | `WRITENR text` | Display without newline |
| `READ` | `READ &VAR` | Read terminal input into variable |

### Control Flow Commands

| Command | Syntax | Description |
|---------|--------|-------------|
| `IF` | `IF &cond THEN action` | Conditional execution |
| `IF/THEN/ELSE` | `IF &cond THEN DO ... END ELSE DO ... END` | Block conditional |
| `DO` / `END` | `DO ... END` | Block delimiter |
| `DO WHILE` | `DO WHILE &cond ... END` | While loop |
| `DO UNTIL` | `DO UNTIL &cond ... END` | Until loop |
| `GOTO` | `GOTO label` | Unconditional branch |
| `EXIT` | `EXIT CODE(rc)` | Terminate with return code |

### Procedure Commands

| Command | Syntax | Description |
|---------|--------|-------------|
| `PROC` | `PROC n parm1 parm2 ... KEY(defaults)` | Define positional and keyword parameters |
| `RETURN` | `RETURN CODE(rc)` | Return from nested CLIST |

### Error/Attention Handling

| Command | Syntax | Description |
|---------|--------|-------------|
| `ERROR` | `ERROR action` | Set error handler |
| `ERROR DO ... END` | (block form) | Multi-statement error handler |
| `ERROR OFF` | | Disable error handling |
| `ATTN` | `ATTN action` | Set attention interrupt handler |
| `ATTN OFF` | | Disable attention handling |

### Control Commands

| Command | Syntax | Description |
|---------|--------|-------------|
| `CONTROL` | `CONTROL LIST/NOLIST` | Show/hide command echo |
| | `CONTROL CONLIST/NOCONLIST` | Show/hide after substitution |
| | `CONTROL MSG/NOMSG` | Show/hide TSO messages |
| | `CONTROL PROMPT/NOPROMPT` | Enable/disable prompting |
| | `CONTROL FLUSH/NOFLUSH` | Flush/keep input on error |
| | `CONTROL END(char)` | Change END delimiter |
| `DATA` / `ENDDATA` | `DATA ... ENDDATA` | Pass data to subcommand |
| `OPENFILE` | `OPENFILE &ddname INPUT/OUTPUT/UPDATE` | Open a file |
| `CLOSFILE` | `CLOSFILE &ddname` | Close a file |
| `GETFILE` | `GETFILE &ddname` | Read a record |
| `PUTFILE` | `PUTFILE &ddname` | Write a record |

## Built-in Functions (25+)

| Function | Description |
|----------|-------------|
| `&SUBSTR(start:end,&string)` | Extract substring |
| `&STR(text)` | Treat as string (prevent evaluation) |
| `&LENGTH(&var)` | Length of string value |
| `&DATATYPE(&var)` | `NUM` or `CHAR` |
| `&EVAL(&expr)` | Force arithmetic evaluation |
| `&NRSTR(text)` | No-rescan string |
| `&SYSDSN('dsname')` | Check dataset existence (returns `OK` or reason) |
| `&SYSTIME` | Current time (HH:MM:SS) |
| `&SYSDATE` | Current date (MM/DD/YY) |
| `&SYSUID` | Current TSO user ID |
| `&SYSPROC` | Current procedure name |
| `&SYSPCMD` | Previous command name |
| `&SYSSCMD` | Previous subcommand name |
| `&SYSNEST` | Nesting level indicator (`YES` or `NO`) |
| `&LASTCC` | Last return code |
| `&MAXCC` | Maximum return code |
| `&SYSSCAN` | Scan limit (symbolic substitution depth) |
| `&SYSLTERM` | Terminal line count |
| `&SYSWTERM` | Terminal line width |
| `&SYSENV` | Execution environment (`FORE` or `BACK`) |
| `&SYSISPF` | ISPF active indicator |
| `&SYSCPU` | CPU time used |
| `&SYSSRV` | Service units used |

## Variable Model

- Variables prefixed with `&`: `&MYVAR`
- Global by default within a CLIST
- `PROC` defines parameters and keyword defaults
- Symbolic substitution: variables replaced in-place before execution
- Compound expressions: `&VAR1.&VAR2` concatenates
- Nesting: `&&&VAR` double-indirection (value of `&VAR` used as variable name)

## TSO Integration

CLISTs can issue any TSO command directly:

| TSO Command | Purpose |
|-------------|---------|
| `ALLOCATE` | Allocate datasets to DD names |
| `FREE` | Free allocated DD names |
| `SUBMIT` | Submit JCL for batch processing |
| `STATUS` | Display job status |
| `LISTDS` | List dataset attributes |
| `LISTCAT` | List catalog entries |
| `DELETE` | Delete a dataset |
| `RENAME` | Rename a dataset |

## Example

```clist
PROC 0 DSN()
CONTROL NOLIST NOMSG
IF &DSN = &STR() THEN DO
  WRITE ENTER DATASET NAME:
  READ &DSN
END
SET &RESULT = &SYSDSN('&DSN')
IF &RESULT = &STR(OK) THEN +
  WRITE DATASET &DSN EXISTS
ELSE +
  WRITE &RESULT
EXIT CODE(0)
```

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn easytrieve_reference() -> String {
    r#"# Easytrieve Plus Language Reference

[Back to Languages](../index.md)

## Overview

Easytrieve Plus is a 4GL designed for report generation and file processing. It minimizes
the code needed for common batch operations like reading files, sorting data, matching
records, and producing formatted reports.

## Program Structure

An Easytrieve program has three sections:

1. **Library Section** - Global definitions (FILE, FIELD, macro)
2. **Job Section** - Processing logic (one or more JOB activities)
3. **Sort Section** - Optional SORT specifications

## FILE/RECORD Definitions

```easytrieve
FILE INFILE
  EMPNO      1  5  N
  EMPNAME    6  30 A
  DEPT       36 3  N
  SALARY     39 8  N  2

FILE OUTFILE PRINTER
```

| Column | Description |
|--------|-------------|
| Field name | User-defined identifier |
| Start position | Starting byte position |
| Length | Field length in bytes |
| Type | `A` (alpha), `N` (numeric), `P` (packed), `B` (binary) |
| Decimals | Decimal places (numeric fields) |

## FIELD Definitions

```easytrieve
W-TOTAL     W  8  N  2  VALUE 0
W-COUNT     W  5  N  0  VALUE 0
W-NAME      W  30 A     VALUE 'UNKNOWN'
```

`W` fields are working storage (not tied to a file).

## Report Generation

```easytrieve
REPORT TITLE 'EMPLOYEE SALARY REPORT'
  SEQUENCE DEPT EMPNAME
  CONTROL DEPT
  LINE EMPNO EMPNAME SALARY
  SUM SALARY
```

### Report Directives

| Directive | Description |
|-----------|-------------|
| `REPORT` | Begin report definition |
| `TITLE` | Report title line(s) |
| `HEADING` | Column heading override |
| `LINE` | Detail line fields |
| `CONTROL` | Control break field(s) |
| `SUM` | Accumulate and print totals |
| `SEQUENCE` | Sort order for report |
| `PAGESIZE` | Lines per page |
| `LINESIZE` | Characters per line |
| `RECAP` | Summary fields only (no detail lines) |

## Control Flow

| Statement | Description |
|-----------|-------------|
| `IF cond ... END-IF` | Conditional execution |
| `IF cond ... ELSE ... END-IF` | If-else |
| `PERFORM proc-name` | Call internal procedure |
| `DO WHILE cond ... END-DO` | While loop |
| `DO count ... END-DO` | Counted loop |
| `GOTO label` | Unconditional branch |
| `STOP` | End processing |

## File Processing

```easytrieve
JOB INPUT INFILE
  IF SALARY > 50000
    PUT OUTFILE
  END-IF
```

### Automatic File Processing
Easytrieve automatically reads records from input files in the `JOB` statement.
The `JOB INPUT` clause specifies which file(s) drive the processing loop.

### Multi-File Operations

| Pattern | Description |
|---------|-------------|
| `JOB INPUT FILE1` | Single file processing |
| `JOB INPUT FILE1 FILE2` | Matched file processing (synchronized) |
| `JOB INPUT NULL` | No automatic input (manual READ) |

## SORT

```easytrieve
SORT INFILE TO SORTFILE USING DEPT EMPNAME
```

Sort can be specified:
- Before a JOB (standalone sort)
- Within REPORT using `SEQUENCE`

## SEARCH (Table Lookup)

```easytrieve
SEARCH TABTABLE WITH EMPNO GIVING DEPTNAME
```

Supports binary search on sorted tables loaded from files or defined inline.

## SQL Bridge

```easytrieve
SQL SELECT EMPNO EMPNAME SALARY
    FROM EMPTABLE
    WHERE DEPT = :W-DEPT
```

Easytrieve can embed SQL for DB2 access, with host variables prefixed by `:`.

## Arithmetic and String Operations

| Operation | Syntax |
|-----------|--------|
| Assignment | `W-TOTAL = SALARY + BONUS` |
| Add | `W-TOTAL = W-TOTAL + SALARY` |
| Subtract | `W-NET = GROSS - TAX` |
| Multiply | `W-RESULT = QTY * PRICE` |
| Divide | `W-AVG = W-TOTAL / W-COUNT` |
| Concatenation | `W-FULL = W-FIRST + ' ' + W-LAST` |

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn natural_reference() -> String {
    r#"# Natural 4GL Language Reference

[Back to Languages](../index.md)

## Overview

Natural is Software AG's 4GL designed for building applications on top of ADABAS
(Adaptable Database System). It features structured programming, map-based screens,
and direct ADABAS integration.

## Data Types (11 Types)

| Type | Code | Description | Example |
|------|------|-------------|---------|
| Alpha | `A` | Alphanumeric string | `#NAME (A20)` |
| Numeric | `N` | Unpacked numeric | `#AMOUNT (N7.2)` |
| Packed | `P` | Packed decimal | `#TOTAL (P11.2)` |
| Binary | `B` | Binary data | `#FLAGS (B4)` |
| Integer | `I` | Binary integer (1/2/4 bytes) | `#COUNT (I4)` |
| Float | `F` | Floating point (4/8 bytes) | `#RATE (F8)` |
| Date | `D` | Date value | `#HIRE-DATE (D)` |
| Time | `T` | Date + time | `#TIMESTAMP (T)` |
| Logical | `L` | Boolean (TRUE/FALSE) | `#FOUND (L)` |
| Control | `C` | Control variable (attribute) | `#ATTR (C)` |
| Unicode | `U` | Unicode string | `#UTEXT (U40)` |

## Program Types

| Type | Suffix | Description |
|------|--------|-------------|
| Program | `P` | Main executable unit |
| Subprogram | `N` | Called via CALLNAT |
| Subroutine | `S` | External subroutine |
| Helproutine | `H` | Online help |
| Map | `M` | Screen definition |
| Global Data Area | `G` | Shared data definitions |
| Local Data Area | `L` | Module-specific data |
| Parameter Data Area | `A` | Parameter definitions |
| Copycode | `C` | Included source |
| Text | `T` | Text object |
| Class | `CL` | OO class definition |
| Function | `FN` | Functional module |
| Adapter | `RA` | Resource adapter |

## DDMs (Data Definition Modules)

DDMs map ADABAS file structures to Natural:

```natural
DB: 20 EMPLOYEES
  1 AA PERSONNEL-ID    A8  /* ADABAS short name, Natural long name */
  1 AB FIRST-NAME      A20
  1 AC LAST-NAME       A20
  1 AD BIRTH           D
```

## Control Flow

### Loops
```natural
FOR #I = 1 TO 100
  /* counted loop */
END-FOR

REPEAT
  /* loop body */
  IF condition THEN ESCAPE BOTTOM END-IF
END-REPEAT

REPEAT WHILE condition
  /* while loop */
END-REPEAT
```

### Conditionals
```natural
IF condition
  THEN statements
  ELSE statements
END-IF

DECIDE FOR FIRST CONDITION
  WHEN condition1  statements
  WHEN condition2  statements
  WHEN NONE        statements
END-DECIDE

DECIDE ON FIRST VALUE OF #VAR
  VALUE 'A'    statements
  VALUE 'B'    statements
  NONE         statements
END-DECIDE
```

### Flow Control
- `ESCAPE BOTTOM` - exit innermost loop
- `ESCAPE TOP` - skip to next iteration
- `ESCAPE ROUTINE` - exit current module
- `ESCAPE MODULE` - terminate module

## Map Definitions

Maps define 3270 screens:

```natural
DEFINE DATA LOCAL
  1 #NAME (A20)
  1 #DEPT (N3)
END-DEFINE

FORMAT LS=80 PS=24
INPUT USING MAP 'EMPMAP'
```

Map fields can have attributes: `AD=M` (modifiable), `AD=O` (output only),
`AD=I` (intensified), `CD=RE` (red), `CD=BL` (blue).

## System Variables (70+)

| Variable | Description |
|----------|-------------|
| `*APPLIC-ID` | Current application name |
| `*COUNTER` | Loop iteration counter |
| `*CPU-TIME` | CPU time used (hundredths of seconds) |
| `*DAT4D` | Current date (YYYY-MM-DD) |
| `*DAT4E` | Current date (MM/DD/YYYY) |
| `*DAT4I` | Current date (YYYY-MM-DD internal) |
| `*DEVICE` | Terminal device type |
| `*ERROR-NR` | Last error number |
| `*ERROR-LINE` | Line number of last error |
| `*INIT-USER` | Initial user ID |
| `*ISN` | Current ADABAS ISN |
| `*LANGUAGE` | Current language code |
| `*LENGTH(field)` | Dynamic length of alpha field |
| `*LEVEL` | Current program level |
| `*LIBRARY-ID` | Current library name |
| `*LINE-COUNT` | Current line number (report) |
| `*LBOUND(array)` | Lower array bound |
| `*UBOUND(array)` | Upper array bound |
| `*NUMBER` | Records in current loop |
| `*OCC(array)` | Number of occurrences |
| `*PAGE-NUMBER` | Current page number (report) |
| `*PF-KEY` | Last PF key pressed |
| `*PF-NAME` | Name assigned to last PF key |
| `*PROGRAM` | Current program name |
| `*SERVER-TYPE` | Server environment type |
| `*TIME` | Current time (HH:II:SS) |
| `*TIMN` | Time as numeric (internal) |
| `*TIMESTMP` | Current timestamp |
| `*TRIM(field)` | Trimmed field value |
| `*USER` | Current user ID |
| `*USER-NAME` | User's full name |

## ADABAS Access Statements

| Statement | Description |
|-----------|-------------|
| `FIND records IN file WITH condition` | Search with search criteria |
| `READ records IN file BY key` | Sequential read by descriptor |
| `READ records IN file BY ISN` | Read by Internal Sequence Number |
| `GET record IN file ISN` | Direct read by ISN |
| `STORE record IN file` | Add a new record |
| `UPDATE record IN file` | Modify current record |
| `DELETE record IN file` | Delete current record |
| `HISTOGRAM field IN file` | Get value distribution |
| `END TRANSACTION` | Commit database changes |
| `BACKOUT TRANSACTION` | Rollback database changes |

### FIND Example
```natural
FIND EMPLOYEES WITH DEPT = 'D11'
  SORTED BY LAST-NAME
  DISPLAY PERSONNEL-ID FIRST-NAME LAST-NAME SALARY
END-FIND
```

### READ Example
```natural
READ EMPLOYEES BY LAST-NAME STARTING FROM 'M'
  IF LAST-NAME < 'M' THEN ESCAPE BOTTOM END-IF
  DISPLAY PERSONNEL-ID LAST-NAME FIRST-NAME
END-READ
```

## Additional Features

- **CALLNAT**: Call subprograms with parameters
- **DEFINE SUBROUTINE / PERFORM**: Internal subroutines
- **COMPRESS**: Concatenate fields with delimiter
- **EXAMINE**: Search/replace in strings
- **MOVE EDITED**: Format conversion with edit masks
- **WRITE / DISPLAY / PRINT**: Output statements
- **INPUT**: Terminal input (full-screen or line mode)
- **STACK**: Data stack operations (TOP, BOTTOM, FORMATTED)

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}

fn focus_reference() -> String {
    r#"# FOCUS 4GL Language Reference

[Back to Languages](../index.md)

## Overview

FOCUS (by Information Builders, now part of TIBCO) is a 4GL for ad-hoc reporting,
data analysis, and application development. It uses a non-procedural approach where
users describe *what* they want rather than *how* to get it.

## Master File Descriptors (MFDs)

MFDs define data sources (like DDL schemas):

```focus
FILENAME=EMPLOYEE, SUFFIX=FOC
  SEGNAME=EMPSEG, SEGTYPE=S1
    FIELDNAME=EMP_ID,    ALIAS=EID,  FORMAT=A8,  INDEX=I
    FIELDNAME=LAST_NAME, ALIAS=LN,   FORMAT=A20
    FIELDNAME=DEPT,      ALIAS=DPT,  FORMAT=A4,  INDEX=I
    FIELDNAME=SALARY,    ALIAS=SAL,  FORMAT=D12.2
    FIELDNAME=HIRE_DATE, ALIAS=HD,   FORMAT=YYMD
```

### Field Formats

| Format | Description | Example |
|--------|-------------|---------|
| `An` | Alphanumeric, n chars | `A20` |
| `In` | Integer, n digits | `I8` |
| `Dn.d` | Decimal, n total, d decimal | `D10.2` |
| `Fn.d` | Floating point | `F12.4` |
| `Pn.d` | Packed decimal | `P8.2` |
| `YYMD` | Date (year-month-day) | `YYMD` |
| `MDY` | Date (month-day-year) | `MDY` |
| `YQ` | Year-quarter | `YQ` |

## TABLE Request

The primary reporting command:

```focus
TABLE FILE EMPLOYEE
  HEADING CENTER
  "EMPLOYEE SALARY REPORT"
  ""
  PRINT EMP_ID LAST_NAME SALARY
  BY DEPT
  WHERE SALARY GT 50000
  ON DEPT SUBFOOT
  "DEPT TOTAL: <SALARY"
  ON TABLE SET PAGE-NUM ON
  END
```

### TABLE Clauses

| Clause | Description |
|--------|-------------|
| `PRINT` | Display detail fields |
| `SUM` | Aggregate (sum) fields |
| `COUNT` | Count records |
| `AVG` | Average value |
| `MAX` / `MIN` | Maximum / minimum |
| `PCT` / `CPCT` | Percentage / cumulative percentage |
| `BY` | Sort/group by field (vertical) |
| `ACROSS` | Cross-tabulate (horizontal) |
| `WHERE` | Filter condition |
| `IF` | Row-level condition |
| `HEADING` | Report heading |
| `FOOTING` | Report footing |
| `SUBHEAD` | Group header |
| `SUBFOOT` | Group footer |
| `ON field` | Control break actions |
| `ON TABLE` | Report-level actions |

### WHERE Operators

| Operator | Description |
|----------|-------------|
| `EQ`, `NE` | Equal, not equal |
| `GT`, `GE` | Greater than, greater or equal |
| `LT`, `LE` | Less than, less or equal |
| `FROM x TO y` | Range |
| `CONTAINS` | Substring match |
| `LIKE` | Pattern match (`_` single, `%` multiple) |
| `IS MISSING` | Null test |
| `AND`, `OR`, `NOT` | Logical operators |

## GRAPH Request

```focus
GRAPH FILE EMPLOYEE
  SUM SALARY
  BY DEPT
  ON GRAPH SET GRID ON
  ON GRAPH SET GRAPHTYPE BAR
  END
```

Graph types: `BAR`, `LINE`, `PIE`, `SCATTER`, `AREA`, `HISTOGRAM`.

## MODIFY Request (Transaction Processing)

```focus
MODIFY FILE EMPLOYEE
  MATCH EMP_ID
  ON MATCH UPDATE SALARY
  ON NOMATCH REJECT
  DATA ON TRANFILE
  END
```

### MODIFY Actions

| Action | Description |
|--------|-------------|
| `UPDATE field` | Update matched record |
| `DELETE` | Delete matched record |
| `ADD` | Add if no match |
| `REJECT` | Reject transaction |
| `TYPE message` | Display message |

## DEFINE and COMPUTE

### DEFINE (Virtual Fields)
```focus
DEFINE FILE EMPLOYEE
  ANNUAL_BONUS/D10.2 = SALARY * 0.10;
  FULL_NAME/A40 = LAST_NAME | ', ' | FIRST_NAME;
END
```

### COMPUTE (In Reports)
```focus
TABLE FILE EMPLOYEE
  SUM SALARY
  COMPUTE BONUS/D10.2 = SALARY * 0.10;
  BY DEPT
  END
```

## Dialogue Manager

The procedural scripting layer for FOCUS:

```focus
-SET &DEPT = 'D11';
-IF &ANS EQ 'Y' GOTO RUNRPT;
-TYPE Enter department code:
-ACCEPT &DEPT
-RUN
-RUNRPT
TABLE FILE EMPLOYEE
  PRINT EMP_ID LAST_NAME SALARY
  WHERE DEPT EQ '&DEPT'
  END
```

### Dialogue Manager Commands

| Command | Description |
|---------|-------------|
| `-SET &var = value` | Set variable |
| `-IF condition action` | Conditional |
| `-GOTO label` | Branch |
| `-TYPE text` | Display text |
| `-ACCEPT &var` | Prompt for input |
| `-RUN` | Execute accumulated request |
| `-INCLUDE procname` | Include procedure |
| `-REPEAT n TIMES ... -ENDREPEAT` | Loop |
| `-FOR &var FROM n TO m ... -ENDFOR` | Counted loop |
| `-WHILE condition ... -ENDWHILE` | While loop |
| `-READ ... -ENDREAD` | Read lines from file |
| `-EXIT` | Terminate procedure |
| `-DECODE &var (val1 result1 val2 result2 ELSE default)` | Lookup |

## IF/THEN/ELSE (In Reports)

```focus
TABLE FILE EMPLOYEE
  PRINT EMP_ID LAST_NAME
  COMPUTE STATUS/A10 =
    IF SALARY GT 100000 THEN 'EXECUTIVE'
    ELSE IF SALARY GT 50000 THEN 'SENIOR'
    ELSE 'STANDARD';
  END
```

## Built-in Functions

### String Functions
`SUBSTR`, `TRIM`, `LTRIM`, `RTRIM`, `UPCASE`, `LOCASE`, `EDIT`,
`PARONE`, `POSIT`, `ARGLEN`, `CTRAN`, `OVRLAY`, `REVERSE`,
`STRREP`, `CHKFMT`

### Numeric Functions
`ABS`, `MAX`, `MIN`, `MOD`, `INT`, `ROUND`, `SQRT`, `EXP`, `LOG`,
`IMOD`, `RDUNIF` (random), `NORMSDST`, `NORMSDF` (statistical)

### Date Functions
`TODAY`, `AYMD`, `ADMY`, `AMDY`, `CHGDAT`, `DTEFMT`, `DATEDIF`,
`DATECVT`, `FIFSDAY`, `LASTDAY`, `HNAME`, `HPART`, `HADD`

### Conversion
`ATODBL`, `DTEFMT`, `FTOA`, `ITOPACK`, `HEXBYT`, `BYTOHEX`,
`ASIS`, `CHAR`, `FPRINT`

---
*Generated by Mainframe Code Wiki*
"#.to_string()
}
