//! Per-source-file program documentation generator.

use std::fs;
use std::path::PathBuf;

use crate::{WikiConfig, WikiResult};

/// Source language type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SourceLanguage {
    Cobol,
    Jcl,
    Rexx,
    Hlasm,
    Pli,
    Clist,
    Easytrieve,
    Natural,
    Focus,
}

impl SourceLanguage {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Cobol => "COBOL",
            Self::Jcl => "JCL",
            Self::Rexx => "REXX",
            Self::Hlasm => "HLASM",
            Self::Pli => "PL/I",
            Self::Clist => "CLIST",
            Self::Easytrieve => "Easytrieve",
            Self::Natural => "Natural",
            Self::Focus => "FOCUS",
        }
    }

    pub fn dir_name(&self) -> &'static str {
        match self {
            Self::Cobol => "cobol/programs",
            Self::Jcl => "jcl/jobs",
            Self::Rexx => "rexx/execs",
            Self::Hlasm => "hlasm/modules",
            Self::Pli => "pli/programs",
            Self::Clist => "clist/scripts",
            Self::Easytrieve => "easytrieve/programs",
            Self::Natural => "natural/programs",
            Self::Focus => "focus/requests",
        }
    }
}

/// Documentation for a single program.
#[derive(Debug, Clone)]
pub struct ProgramDoc {
    pub name: String,
    pub language: SourceLanguage,
    pub source_path: PathBuf,
    pub lines: usize,
    pub complexity: Option<String>,
    pub features: Vec<String>,
}

impl ProgramDoc {
    /// Build a ProgramDoc from an assess AnalysisResult.
    pub fn from_analysis(result: &open_mainframe_assess::AnalysisResult) -> Self {
        let name = result
            .program_id
            .clone()
            .unwrap_or_else(|| result.file_name.clone());
        let features: Vec<String> = result.features.iter().map(|f| f.name.clone()).collect();
        Self {
            name,
            language: SourceLanguage::Cobol,
            source_path: PathBuf::from(&result.file_name),
            lines: result.metrics.total_lines,
            complexity: Some(format!("{:?}", result.complexity)),
            features,
        }
    }
}

/// Generate per-program documentation pages.
pub fn generate_program_pages(config: &WikiConfig, programs: &[ProgramDoc]) -> WikiResult<()> {
    for prog in programs {
        let dir = config
            .output_dir
            .join("languages")
            .join(prog.language.dir_name());
        fs::create_dir_all(&dir)?;
        let path = dir.join(format!("{}.md", prog.name));
        let content = render_program_page(prog);
        fs::write(&path, content)?;
    }
    Ok(())
}

fn render_program_page(prog: &ProgramDoc) -> String {
    let mut md = String::new();
    md.push_str(&format!("# {}\n\n", prog.name));

    // Navigation
    md.push_str(&format!(
        "[Back to {} Programs](../../languages/{}/index.md)\n\n",
        prog.language.label(),
        match prog.language {
            SourceLanguage::Cobol => "cobol",
            SourceLanguage::Jcl => "jcl",
            SourceLanguage::Rexx => "rexx",
            SourceLanguage::Hlasm => "hlasm",
            SourceLanguage::Pli => "pli",
            SourceLanguage::Clist => "clist",
            SourceLanguage::Easytrieve => "easytrieve",
            SourceLanguage::Natural => "natural",
            SourceLanguage::Focus => "focus",
        }
    ));

    // Summary section
    md.push_str("## Summary\n\n");
    md.push_str("| Metric | Value |\n");
    md.push_str("|--------|-------|\n");
    md.push_str(&format!("| Language | {} |\n", prog.language.label()));
    md.push_str(&format!("| Total Lines | {} |\n", prog.lines));
    if let Some(ref cx) = prog.complexity {
        md.push_str(&format!("| Complexity | {} |\n", cx));
    }
    md.push_str(&format!(
        "| Features | {} |\n",
        prog.features.len()
    ));
    md.push('\n');

    // Source location
    md.push_str("## Source Location\n\n");
    md.push_str(&format!("`{}`\n\n", prog.source_path.display()));

    // Features table
    if !prog.features.is_empty() {
        md.push_str("## Features Detected\n\n");
        md.push_str("| # | Feature |\n");
        md.push_str("|---|----------|\n");
        for (i, f) in prog.features.iter().enumerate() {
            md.push_str(&format!("| {} | {} |\n", i + 1, f));
        }
        md.push('\n');
    }

    md.push_str("---\n*Generated by Mainframe Code Wiki*\n");
    md
}
